/** @module contracts/http — REST DTOs, list queries, health and the endpoint manifest (spec 03 §4–5) */

export {
  SCREENSHOT_CACHE_CONTROL,
  ScreenshotKind,
  ScreenshotRow,
  ScreenshotSortKey,
  ScreenshotsPage,
  SessionEventParams,
  SessionScreenshotsQuery,
} from './artifacts.ts';
export {
  AttentionDecision,
  AttentionPage,
  AttentionQuery,
  AttentionSortKey,
  BULK_REQUESTS_MAX,
  BulkAttentionRequest,
  BulkRequestResult,
  BulkRequestsResponse,
  BulkVaultConfirmRequest,
  OPERATOR_MESSAGE_MAX,
  OperatorRequestRow,
  RequestIdParams,
  ResolveAttentionRequest,
  ResolveRequestResponse,
  ResolveVaultConfirmRequest,
  SessionAttentionPage,
  SessionAttentionQuery,
  VaultConfirmDecision,
  VaultConfirmPage,
  VaultConfirmQuery,
} from './attention.ts';
export {
  ApiTokenList,
  ApiTokenSummary,
  AuthPrincipal,
  AuthSessionIdPrefixParams,
  AuthSessionInfo,
  AuthSessionList,
  AuthSessionSummary,
  BEARER_TOKEN_RE,
  ChangePasswordRequest,
  ChangePasswordResponse,
  CreateGrantRequest,
  CreateGrantResponse,
  CreateTokenRequest,
  CreateTokenResponse,
  CredentialIdParams,
  GrantQuery,
  GrantRoute,
  LoginRequest,
  LoginResponse,
  LogoutResponse,
  MeResponse,
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  RevokeAllSessionsResponse,
  TokenOwnerKind,
} from './auth.ts';
export {
  BlockedAttemptsPage,
  BlockedAttemptsQuery,
  BlockedRequestRow,
  BlockedSortKey,
  BlocklistOverview,
  BlocklistOverviewQuery,
  BlocklistPattern,
  BlocklistSkippedLine,
  BlocklistStats,
  ReloadBlocklistResponse,
} from './blocklist.ts';
export type { Page } from './common.ts';
export {
  AppliedQuery,
  BootPhase,
  BulkItemError,
  Bytes,
  Count,
  CURSOR_MAX_LENGTH,
  Cursor,
  csv,
  DurationMs,
  EpochMs,
  Facet,
  HealthCheckState,
  HealthResponse,
  HealthStatus,
  IdempotencyKey,
  IfMatchVersion,
  LIMIT_DEFAULT,
  LIMIT_MAX,
  limitQuery,
  listQuery,
  OkResponse,
  PageInfo,
  PageQuery,
  ProblemDetails,
  page,
  QueryBool,
  QueryEpochMs,
  QueryInt,
  QueryText,
  ResponseMeta,
  SortDir,
  sortable,
  TimeWindow,
  windowQuery,
} from './common.ts';
export type { HttpEndpoint, HttpMethod } from './endpoints.ts';
export {
  API_PREFIX,
  findEndpoint,
  HTTP_ENDPOINTS,
  PASSWORD_CHANGE_ALLOWED_OPERATIONS,
} from './endpoints.ts';
export {
  LOGS_LIMIT_MAX,
  LogRecord,
  LogsExportQuery,
  LogsPage,
  LogsQuery,
  LogTransport,
  SerializedError,
} from './logs.ts';
export {
  ACTIVITY_BUCKET_MAX_MS,
  ACTIVITY_BUCKET_MIN_MS,
  ACTIVITY_DEFAULT_WINDOW_MS,
  ACTIVITY_MAX_BUCKETS,
  ActivityBucket,
  ActivityGroupBy,
  ActivityQuery,
  ActivityResponse,
  ActivitySummary,
  HarnessMetricRow,
  HarnessMetricsQuery,
  HarnessMetricsResponse,
  ToolMetricRow,
  ToolMetricsGroupBy,
  ToolMetricsQuery,
  ToolMetricsResponse,
} from './metrics.ts';
export {
  Notification,
  NotificationAckResponse,
  NotificationIdParams,
  NotificationsPage,
  NotificationsQuery,
  NotificationsUpdatedResponse,
  PREFERENCES_MAX_BYTES,
  Preferences,
  PreferencesResponse,
  PutPreferencesRequest,
  PutPreferencesResponse,
  SavedView,
} from './notifications.ts';
export {
  DomainCount,
  FleetPageRow,
  PageDomainsQuery,
  PageDomainsResponse,
  PageRow,
  PageSortKey,
  PagesPage,
  PagesQuery,
  RecentPagesQuery,
  RecentPagesResponse,
  SessionPagesPage,
  SessionPagesQuery,
} from './pages.ts';
export { ClientErrorReport, SearchQuery, SearchResponse } from './search.ts';
export {
  ArchiveSessionResponse,
  BULK_SESSIONS_MAX,
  BulkSessionAction,
  BulkSessionResult,
  BulkSessionsRequest,
  BulkSessionsResponse,
  DeleteSessionResponse,
  EXPORT_MEDIA_TYPES,
  InputRejectionCode,
  RevealDataDirResponse,
  RevealFailureReason,
  SESSION_EXPORT_MAX_ROWS,
  SessionExportQuery,
  SessionInputRequest,
  SessionInputResponse,
  SessionTraceInfo,
  SetViewportRequest,
  SetViewportResponse,
  TerminateSessionResponse,
  TimelineKind,
  TraceUnavailableDetails,
  VIEWPORT_MAX,
  VIEWPORT_MIN,
  ViewportDimension,
} from './session-actions.ts';
export {
  AppliedIdentity,
  ArchivedFilter,
  Engine,
  HarnessSlug,
  SessionClient,
  SessionCounts,
  SessionDataDir,
  SessionDetail,
  SessionFacets,
  SessionIdParams,
  SessionSortKey,
  SessionSummary,
  SessionsPage,
  SessionsQuery,
  SessionTraceSummary,
  SessionView,
} from './sessions.ts';
export {
  HarnessConflict,
  LOG_LEVEL_SPEC_RE,
  MCP_CONNECTIONS_LIMIT_DEFAULT,
  MCP_CONNECTIONS_LIMIT_MAX,
  McpConnectionRow,
  McpConnectionsQuery,
  McpConnectionsResponse,
  MigrationRow,
  REDACTED,
  RealtimeConnection,
  RetentionStatus,
  SetLogLevelRequest,
  SetLogLevelResponse,
  StorageStatus,
  SystemBrowser,
  SystemBrowserChannel,
  SystemCapacity,
  SystemConfigKey,
  SystemConfigRef,
  SystemConfigResponse,
  SystemEvent,
  SystemEventsPage,
  SystemEventsQuery,
  SystemInfo,
  SystemRealtimeResponse,
} from './system.ts';
export { TimelineItem, TimelinePage, TimelineQuery } from './timeline.ts';
export {
  FleetToolCallRow,
  SessionToolCallsPage,
  SessionToolCallsQuery,
  ToolCallDetail,
  ToolCallRow,
  ToolCallSortKey,
  ToolCallsPage,
  ToolCallsQuery,
  ToolName,
} from './tool-calls.ts';
export {
  GroupIdParams,
  LockVaultResponse,
  PutGroupPolicyRequest,
  PutGroupPolicyResponse,
  SyncVaultResponse,
  UNGROUPED_GROUP_KEY,
  UnlockVaultRequest,
  UnlockVaultResponse,
  VaultAccessMode,
  VaultCapabilities,
  VaultGroup,
  VaultGrouping,
  VaultGroupPolicy,
  VaultGroupsResponse,
  VaultItem,
  VaultItemsPage,
  VaultItemsQuery,
  VaultOverview,
  VaultStatus,
  VaultUnlockDescriptor,
  VaultUnlockMode,
} from './vault.ts';
export {
  DeleteVaultBindingResponse,
  HandleParams,
  ImportVaultQuery,
  ImportVaultResponse,
  OriginCheck,
  PutVaultBindingRequest,
  PutVaultBindingResponse,
  ResolveBindingsRequest,
  ResolveBindingsResponse,
  VAULT_EXPORT_VERSION,
  VAULT_HANDLE_RE,
  VaultAccessResult,
  VaultAccessRow,
  VaultBinding,
  VaultBindingExport,
  VaultBindingsPage,
  VaultBindingsQuery,
  VaultExportDocument,
  VaultGroupPolicyExport,
  VaultHandle,
  VaultLogPage,
  VaultLogQuery,
  VaultLogSortKey,
} from './vault-bindings.ts';
