/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthRouteImport } from './routes/_auth';
import { Route as PublicRouteImport } from './routes/_public';
import { Route as ThemeRouteImport } from './routes/theme';
import { Route as AuthAttentionRouteImport } from './routes/_auth/attention';
import { Route as AuthBlocklistRouteImport } from './routes/_auth/blocklist';
import { Route as AuthLogsRouteImport } from './routes/_auth/logs';
import { Route as AuthNavigationRouteImport } from './routes/_auth/navigation';
import { Route as AuthNotificationsRouteImport } from './routes/_auth/notifications';
import { Route as AuthOverviewRouteImport } from './routes/_auth/overview';
import { Route as AuthSessionsRouteImport } from './routes/_auth/sessions';
import { Route as AuthSystemRouteImport } from './routes/_auth/system';
import { Route as AuthVaultRouteImport } from './routes/_auth/vault';
import { Route as AuthWebsitesRouteImport } from './routes/_auth/websites';
import { Route as PublicChangePasswordRouteImport } from './routes/_public/change-password';
import { Route as PublicLoginRouteImport } from './routes/_public/login';
import { Route as AuthSessionsIdRouteImport } from './routes/_auth/sessions_.$id';
import { Route as AuthVaultLogRouteImport } from './routes/_auth/vault_.log';
import { Route as AuthSessionsIdLiveRouteImport } from './routes/_auth/sessions_.$id_.live';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any);
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any);
const ThemeRoute = ThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthAttentionRoute = AuthAttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => AuthRoute,
} as any);
const AuthBlocklistRoute = AuthBlocklistRouteImport.update({
  id: '/blocklist',
  path: '/blocklist',
  getParentRoute: () => AuthRoute,
} as any);
const AuthLogsRoute = AuthLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthRoute,
} as any);
const AuthNavigationRoute = AuthNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AuthRoute,
} as any);
const AuthNotificationsRoute = AuthNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthRoute,
} as any);
const AuthOverviewRoute = AuthOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthRoute,
} as any);
const AuthSessionsRoute = AuthSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthRoute,
} as any);
const AuthSystemRoute = AuthSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthRoute,
} as any);
const AuthVaultRoute = AuthVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthRoute,
} as any);
const AuthWebsitesRoute = AuthWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => AuthRoute,
} as any);
const PublicChangePasswordRoute = PublicChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => PublicRoute,
} as any);
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any);
const AuthSessionsIdRoute = AuthSessionsIdRouteImport.update({
  id: '/sessions_/$id',
  path: '/sessions/$id',
  getParentRoute: () => AuthRoute,
} as any);
const AuthVaultLogRoute = AuthVaultLogRouteImport.update({
  id: '/vault_/log',
  path: '/vault/log',
  getParentRoute: () => AuthRoute,
} as any);
const AuthSessionsIdLiveRoute = AuthSessionsIdLiveRouteImport.update({
  id: '/sessions_/$id_/live',
  path: '/sessions/$id/live',
  getParentRoute: () => AuthRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/theme': typeof ThemeRoute;
  '/attention': typeof AuthAttentionRoute;
  '/blocklist': typeof AuthBlocklistRoute;
  '/logs': typeof AuthLogsRoute;
  '/navigation': typeof AuthNavigationRoute;
  '/notifications': typeof AuthNotificationsRoute;
  '/overview': typeof AuthOverviewRoute;
  '/sessions': typeof AuthSessionsRoute;
  '/system': typeof AuthSystemRoute;
  '/vault': typeof AuthVaultRoute;
  '/websites': typeof AuthWebsitesRoute;
  '/change-password': typeof PublicChangePasswordRoute;
  '/login': typeof PublicLoginRoute;
  '/sessions/$id': typeof AuthSessionsIdRoute;
  '/vault/log': typeof AuthVaultLogRoute;
  '/sessions/$id/live': typeof AuthSessionsIdLiveRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/theme': typeof ThemeRoute;
  '/attention': typeof AuthAttentionRoute;
  '/blocklist': typeof AuthBlocklistRoute;
  '/logs': typeof AuthLogsRoute;
  '/navigation': typeof AuthNavigationRoute;
  '/notifications': typeof AuthNotificationsRoute;
  '/overview': typeof AuthOverviewRoute;
  '/sessions': typeof AuthSessionsRoute;
  '/system': typeof AuthSystemRoute;
  '/vault': typeof AuthVaultRoute;
  '/websites': typeof AuthWebsitesRoute;
  '/change-password': typeof PublicChangePasswordRoute;
  '/login': typeof PublicLoginRoute;
  '/sessions/$id': typeof AuthSessionsIdRoute;
  '/vault/log': typeof AuthVaultLogRoute;
  '/sessions/$id/live': typeof AuthSessionsIdLiveRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_auth': typeof AuthRouteWithChildren;
  '/_public': typeof PublicRouteWithChildren;
  '/theme': typeof ThemeRoute;
  '/_auth/attention': typeof AuthAttentionRoute;
  '/_auth/blocklist': typeof AuthBlocklistRoute;
  '/_auth/logs': typeof AuthLogsRoute;
  '/_auth/navigation': typeof AuthNavigationRoute;
  '/_auth/notifications': typeof AuthNotificationsRoute;
  '/_auth/overview': typeof AuthOverviewRoute;
  '/_auth/sessions': typeof AuthSessionsRoute;
  '/_auth/system': typeof AuthSystemRoute;
  '/_auth/vault': typeof AuthVaultRoute;
  '/_auth/websites': typeof AuthWebsitesRoute;
  '/_public/change-password': typeof PublicChangePasswordRoute;
  '/_public/login': typeof PublicLoginRoute;
  '/_auth/sessions_/$id': typeof AuthSessionsIdRoute;
  '/_auth/vault_/log': typeof AuthVaultLogRoute;
  '/_auth/sessions_/$id_/live': typeof AuthSessionsIdLiveRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/theme'
    | '/attention'
    | '/blocklist'
    | '/logs'
    | '/navigation'
    | '/notifications'
    | '/overview'
    | '/sessions'
    | '/system'
    | '/vault'
    | '/websites'
    | '/change-password'
    | '/login'
    | '/sessions/$id'
    | '/vault/log'
    | '/sessions/$id/live';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/theme'
    | '/attention'
    | '/blocklist'
    | '/logs'
    | '/navigation'
    | '/notifications'
    | '/overview'
    | '/sessions'
    | '/system'
    | '/vault'
    | '/websites'
    | '/change-password'
    | '/login'
    | '/sessions/$id'
    | '/vault/log'
    | '/sessions/$id/live';
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_public'
    | '/theme'
    | '/_auth/attention'
    | '/_auth/blocklist'
    | '/_auth/logs'
    | '/_auth/navigation'
    | '/_auth/notifications'
    | '/_auth/overview'
    | '/_auth/sessions'
    | '/_auth/system'
    | '/_auth/vault'
    | '/_auth/websites'
    | '/_public/change-password'
    | '/_public/login'
    | '/_auth/sessions_/$id'
    | '/_auth/vault_/log'
    | '/_auth/sessions_/$id_/live';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  PublicRoute: typeof PublicRouteWithChildren;
  ThemeRoute: typeof ThemeRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_public': {
      id: '/_public';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PublicRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/theme': {
      id: '/theme';
      path: '/theme';
      fullPath: '/theme';
      preLoaderRoute: typeof ThemeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_auth/attention': {
      id: '/_auth/attention';
      path: '/attention';
      fullPath: '/attention';
      preLoaderRoute: typeof AuthAttentionRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/blocklist': {
      id: '/_auth/blocklist';
      path: '/blocklist';
      fullPath: '/blocklist';
      preLoaderRoute: typeof AuthBlocklistRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/logs': {
      id: '/_auth/logs';
      path: '/logs';
      fullPath: '/logs';
      preLoaderRoute: typeof AuthLogsRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/navigation': {
      id: '/_auth/navigation';
      path: '/navigation';
      fullPath: '/navigation';
      preLoaderRoute: typeof AuthNavigationRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/notifications': {
      id: '/_auth/notifications';
      path: '/notifications';
      fullPath: '/notifications';
      preLoaderRoute: typeof AuthNotificationsRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/overview': {
      id: '/_auth/overview';
      path: '/overview';
      fullPath: '/overview';
      preLoaderRoute: typeof AuthOverviewRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/sessions': {
      id: '/_auth/sessions';
      path: '/sessions';
      fullPath: '/sessions';
      preLoaderRoute: typeof AuthSessionsRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/system': {
      id: '/_auth/system';
      path: '/system';
      fullPath: '/system';
      preLoaderRoute: typeof AuthSystemRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/vault': {
      id: '/_auth/vault';
      path: '/vault';
      fullPath: '/vault';
      preLoaderRoute: typeof AuthVaultRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/websites': {
      id: '/_auth/websites';
      path: '/websites';
      fullPath: '/websites';
      preLoaderRoute: typeof AuthWebsitesRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_public/change-password': {
      id: '/_public/change-password';
      path: '/change-password';
      fullPath: '/change-password';
      preLoaderRoute: typeof PublicChangePasswordRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/login': {
      id: '/_public/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof PublicLoginRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_auth/sessions_/$id': {
      id: '/_auth/sessions_/$id';
      path: '/sessions/$id';
      fullPath: '/sessions/$id';
      preLoaderRoute: typeof AuthSessionsIdRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/vault_/log': {
      id: '/_auth/vault_/log';
      path: '/vault/log';
      fullPath: '/vault/log';
      preLoaderRoute: typeof AuthVaultLogRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/sessions_/$id_/live': {
      id: '/_auth/sessions_/$id_/live';
      path: '/sessions/$id/live';
      fullPath: '/sessions/$id/live';
      preLoaderRoute: typeof AuthSessionsIdLiveRouteImport;
      parentRoute: typeof AuthRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthAttentionRoute: typeof AuthAttentionRoute;
  AuthBlocklistRoute: typeof AuthBlocklistRoute;
  AuthLogsRoute: typeof AuthLogsRoute;
  AuthNavigationRoute: typeof AuthNavigationRoute;
  AuthNotificationsRoute: typeof AuthNotificationsRoute;
  AuthOverviewRoute: typeof AuthOverviewRoute;
  AuthSessionsRoute: typeof AuthSessionsRoute;
  AuthSystemRoute: typeof AuthSystemRoute;
  AuthVaultRoute: typeof AuthVaultRoute;
  AuthWebsitesRoute: typeof AuthWebsitesRoute;
  AuthSessionsIdRoute: typeof AuthSessionsIdRoute;
  AuthVaultLogRoute: typeof AuthVaultLogRoute;
  AuthSessionsIdLiveRoute: typeof AuthSessionsIdLiveRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAttentionRoute: AuthAttentionRoute,
  AuthBlocklistRoute: AuthBlocklistRoute,
  AuthLogsRoute: AuthLogsRoute,
  AuthNavigationRoute: AuthNavigationRoute,
  AuthNotificationsRoute: AuthNotificationsRoute,
  AuthOverviewRoute: AuthOverviewRoute,
  AuthSessionsRoute: AuthSessionsRoute,
  AuthSystemRoute: AuthSystemRoute,
  AuthVaultRoute: AuthVaultRoute,
  AuthWebsitesRoute: AuthWebsitesRoute,
  AuthSessionsIdRoute: AuthSessionsIdRoute,
  AuthVaultLogRoute: AuthVaultLogRoute,
  AuthSessionsIdLiveRoute: AuthSessionsIdLiveRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface PublicRouteChildren {
  PublicChangePasswordRoute: typeof PublicChangePasswordRoute;
  PublicLoginRoute: typeof PublicLoginRoute;
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicChangePasswordRoute: PublicChangePasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
};

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ThemeRoute: ThemeRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
