/** @module test/docs/docs-gates — docs gates: generated references are fresh and complete, links resolve, no unsupported flag spellings */
import { describe, expect, it } from 'bun:test';
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { CONFIG_KEYS } from '@browserhive/contracts/config';
import { ERROR_CODES } from '@browserhive/contracts/errors';
import { HTTP_ENDPOINTS } from '@browserhive/contracts/http';
import { ALL_TOOL_NAMES } from '@browserhive/contracts/tools';
import { WS_STATIC_TOPICS } from '@browserhive/contracts/ws';

const ROOT = resolve(import.meta.dir, '../..');
const REFERENCE = join(ROOT, 'docs/reference');

function markdownFiles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .sort()
    .flatMap((name) => {
      const path = join(dir, name);
      if (statSync(path).isDirectory()) return markdownFiles(path);
      return name.endsWith('.md') ? [path] : [];
    });
}

/** Every Markdown file whose relative links are checked. */
const LINKED_FILES = [
  ...markdownFiles(join(ROOT, 'docs')),
  join(ROOT, 'README.md'),
  join(ROOT, 'packages/browserhive/README.md'),
  join(ROOT, 'CHANGELOG.md'),
].filter((path) => existsSync(path));

/** Hand-written user-facing prose that must not mention unsupported flag spellings. */
const PROSE_FILES = [
  ...markdownFiles(join(ROOT, 'docs/guide')),
  ...markdownFiles(join(ROOT, 'docs/contributing')),
  join(ROOT, 'docs/README.md'),
  join(ROOT, 'README.md'),
  join(ROOT, 'packages/browserhive/README.md'),
].filter((path) => existsSync(path));

/** Unsupported flag and environment variable spellings (D-02, D-06, spec 08 §5.5). */
const UNSUPPORTED_SPELLINGS = [
  '--admin-port',
  '--admin-bind',
  '--pretty-logs',
  '--log-pretty',
  '--allow-evaluate',
  '--max-sessions',
  '--data-dir',
  '--session-lease',
  '--default-headless',
  '--default-channel',
  '--allow-insecure-bind',
  '--min-attention-wait',
  '--dry-run',
  'BROWSERHIVE_ADMIN_PORT',
  'BROWSERHIVE_ADMIN_BIND',
  'BROWSERHIVE_LOG_PRETTY',
  'BROWSERHIVE_DISABLE_PATCHRIGHT',
];

function read(path: string): string {
  return readFileSync(path, 'utf8');
}

function stripCode(markdown: string): string {
  return markdown.replace(/```[\s\S]*?```/g, '').replace(/`[^`\n]*`/g, '');
}

function slug(heading: string): string {
  return heading
    .replace(/`/g, '')
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    .trim()
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s_-]/gu, '')
    .replace(/\s/g, '-');
}

const anchorCache = new Map<string, ReadonlySet<string>>();

function anchorsOf(path: string): ReadonlySet<string> {
  const cached = anchorCache.get(path);
  if (cached !== undefined) return cached;
  const text = read(path);
  const anchors = new Set<string>();
  for (const match of text.matchAll(/\bid="([^"]+)"/g)) {
    if (match[1] !== undefined) anchors.add(match[1]);
  }
  const counts = new Map<string, number>();
  for (const match of text.replace(/```[\s\S]*?```/g, '').matchAll(/^#{1,6}\s+(.+)$/gm)) {
    const base = slug(match[1] ?? '');
    const seen = counts.get(base) ?? 0;
    anchors.add(seen === 0 ? base : `${base}-${seen}`);
    counts.set(base, seen + 1);
  }
  anchorCache.set(path, anchors);
  return anchors;
}

function brokenLinks(file: string): string[] {
  const broken: string[] = [];
  const text = stripCode(read(file));
  for (const match of text.matchAll(/\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g)) {
    const target = match[1] ?? '';
    if (/^[a-z][a-z0-9+.-]*:/i.test(target) || target.startsWith('<')) continue;
    const [pathPart = '', fragment] = target.split('#', 2);
    const destination = pathPart === '' ? file : resolve(dirname(file), pathPart);
    const where = `${relative(ROOT, file)} → ${target}`;
    if (!existsSync(destination)) {
      broken.push(`${where} (missing file)`);
      continue;
    }
    if (fragment !== undefined && fragment !== '' && destination.endsWith('.md')) {
      if (!anchorsOf(destination).has(fragment)) broken.push(`${where} (missing anchor)`);
    }
  }
  return broken;
}

describe('generated references', () => {
  it('are up to date (gen-docs --check)', () => {
    const run = Bun.spawnSync(['bun', 'scripts/gen-docs.ts', '--check'], { cwd: ROOT });
    expect({ exitCode: run.exitCode, stderr: run.stderr.toString() }).toEqual({
      exitCode: 0,
      stderr: '',
    });
  });

  it('start with the generated header', () => {
    for (const name of ['configuration.md', 'errors.md', 'tools.md', 'api.md', 'websocket.md']) {
      expect(read(join(REFERENCE, name)).split('\n')[0]).toBe(
        '<!-- generated by scripts/gen-docs.ts; do not edit -->',
      );
    }
  });

  it('document every error code with an anchor', () => {
    const anchors = anchorsOf(join(REFERENCE, 'errors.md'));
    expect(ERROR_CODES.filter((code) => !anchors.has(code))).toEqual([]);
  });

  it('document every config key with an anchor', () => {
    const anchors = anchorsOf(join(REFERENCE, 'configuration.md'));
    expect(CONFIG_KEYS.filter((key) => !anchors.has(key))).toEqual([]);
  });

  it('document every tool with an anchor', () => {
    const anchors = anchorsOf(join(REFERENCE, 'tools.md'));
    expect(ALL_TOOL_NAMES.filter((name) => !anchors.has(name))).toEqual([]);
  });

  it('document every REST operation and WS topic', () => {
    const api = read(join(REFERENCE, 'api.md'));
    expect(HTTP_ENDPOINTS.filter((e) => !api.includes(`\`${e.operationId}\``))).toEqual([]);
    const ws = read(join(REFERENCE, 'websocket.md'));
    expect(WS_STATIC_TOPICS.filter((topic) => !ws.includes(`\`${topic}\``))).toEqual([]);
  });

  it('ship the config file JSON Schema', () => {
    const schema: unknown = JSON.parse(read(join(REFERENCE, 'config.schema.json')));
    expect(schema).toMatchObject({ title: 'BrowserHive configuration file' });
  });
});

describe('hand-written docs', () => {
  it('exist', () => {
    expect(PROSE_FILES.length).toBeGreaterThan(10);
  });

  it('have no broken relative links or anchors', () => {
    expect(LINKED_FILES.flatMap(brokenLinks)).toEqual([]);
  });

  it('mention no unsupported flag spellings', () => {
    const hits: string[] = [];
    for (const file of PROSE_FILES) {
      const text = read(file);
      for (const banned of UNSUPPORTED_SPELLINGS) {
        if (text.includes(banned)) hits.push(`${relative(ROOT, file)}: ${banned}`);
      }
    }
    expect(hits).toEqual([]);
  });

  it('use no kebab-case flags on browserhive command lines', () => {
    const hits: string[] = [];
    for (const file of PROSE_FILES) {
      for (const line of read(file).split('\n')) {
        if (!/\bbrowserhive\s+-{0,2}[a-z]/.test(line)) continue;
        const command = line.slice(line.search(/\bbrowserhive\s/));
        for (const flag of command.matchAll(/(?<![\w-])--[a-z]+(?:-[a-z]+)+\b/g)) {
          hits.push(`${relative(ROOT, file)}: ${flag[0]} in "${line.trim()}"`);
        }
      }
    }
    expect(hits).toEqual([]);
  });
});
