/** @module contracts — root entry: every public symbol of every subpath, by name (no `export *`) */

export {
  isSensitive,
  SENSITIVE_META_KEY,
  sensitive,
} from './common/index.ts';
export {
  CONFIG_FILE_SCHEMA_ID,
  CONFIG_GROUPS,
  CONFIG_KEYS,
  CONFIG_REF_DEF,
  CONFIG_REF_PATTERN,
  CONFIG_SHAPE,
  type ConfigGroup,
  type ConfigKey,
  type CrossFieldIssue,
  configFileJsonSchema,
  crossFieldIssues,
  DERIVED_SOURCES,
  type DefaultKeyMeta,
  type Derived,
  type DerivedKeyMeta,
  type DerivedSource,
  derived,
  ENV_PREFIX,
  type EnvLookup,
  type Expansion,
  type ExplicitKeys,
  envNameOf,
  expandRefs,
  firstRefLike,
  formatBytes,
  formatDuration,
  formatLevelSpec,
  formatRefNames,
  formatShadowLine,
  GRAMMAR_META_KEY,
  grammarFail,
  grammarOf,
  IDENTITY_ENV_VARS,
  type IdentityEnvVar,
  isIdentityEnvVar,
  isInsecureBind,
  isIPv4,
  isIPv6,
  isKeyMeta,
  isLoopbackHost,
  KEY_ALIASES,
  type KeyLookup,
  type KeyMeta,
  type KeyMetaInput,
  type KeyNames,
  type KeyProvenance,
  key,
  keyMeta,
  keysInGroup,
  type LevelSpec,
  LOGGING_KEYS,
  lookupKey,
  type MaxSessions,
  NO_EXPLICIT_KEYS,
  namesFor,
  type OptionalKeyMeta,
  type Provenance,
  parseKeyMeta,
  RECORDING_KEYS,
  REF_FORMS,
  REF_SCHEMES,
  RESERVED_CONFIG_KEYS,
  RESERVED_ENUM_MEMBERS,
  type RefProblem,
  type RefScheme,
  type RefToken,
  type ReservedConfigKey,
  readKeyMeta,
  refTokenText,
  reservedMessage,
  SERVER_KEYS,
  SESSION_KEYS,
  type ServerConfig,
  type ServerConfigInput,
  type ShadowLine,
  STEALTH_KEYS,
  type SuppliedValue,
  scanRefs,
  secretKeys,
  serverConfigObject,
  serverConfigSchema,
  serverConfigSchemaFor,
  shadowLabel,
  sourceWithRefs,
  TELEMETRY_KEYS,
  type ValueRef,
  viaRefs,
  zBool,
  zBytes,
  zDuration,
  zEnumOf,
  zHost,
  zInt,
  zLevelSpec,
  zList,
  zMap,
  zMaxSessions,
  zPath,
  zPort,
  zRatio,
  zReservedEnum,
  zString,
  zUrl,
} from './config/index.ts';
export {
  ActorKind,
  AttentionMode,
  AttentionStatus,
  AuthMethod,
  AuthMode,
  BlockedSource,
  CaptchaMode,
  Channel,
  ClosedReason,
  ContextTransport,
  CredentialKind,
  DegradationSeverity,
  ErrorCategory,
  LogColor,
  LogFormat,
  LogLevel,
  LogPersist,
  NotificationSeverity,
  NotificationType,
  OperatorRequestKind,
  OperatorRequestStatus,
  OtelProtocol,
  OtelSignal,
  PersistenceMode,
  PrincipalKind,
  ProvenanceSource,
  RecordToolResults,
  Retryable,
  SavedAuthKind,
  Scope,
  SessionStatus,
  StealthDriver,
  StealthDriverName,
  StealthLevel,
  ToolCapability,
  Transport,
  UrlCategory,
  VaultBackendKind,
} from './enums/index.ts';
export {
  AUDIT_ERRORS,
  AUTH_ERRORS,
  type AuditCode,
  BOOT_ERRORS,
  type BootExitCode,
  codesInCategory,
  defineError,
  ERROR_CODES,
  ERROR_DOCS_URL,
  ERROR_REGISTRY,
  type ErrorCode,
  ErrorCodeSchema,
  type ErrorDetails,
  type ErrorSpec,
  type ErrorSpecShape,
  errorDocsUrl,
  errorSpec,
  type HttpAuditCode,
  httpAuditCode,
  httpAuditStatus,
  isErrorCode,
  isHttpAuditCode,
  McpErrorContent,
  PAGE_ERRORS,
  ProblemDetails,
  renderMessage,
  SERVICE_ERRORS,
  SESSION_ERRORS,
  SessionWarningDetails,
  TRANSPORT_ERRORS,
  WARNING_ERRORS,
  WsErrorPayload,
} from './errors/index.ts';
export {
  type CappedMeta,
  CLIENT_NAME_ALIASES,
  capMetaBag,
  DECLARED_SOURCES,
  type DeclaredSource,
  GENERIC_CLIENT_NAMES,
  HARNESS_LABELS,
  HARNESS_QUERY_PARAM,
  HARNESS_SLUG_MAX,
  HARNESS_SLUGS,
  HARNESS_SOURCE_LABELS,
  HARNESS_SOURCES,
  type HarnessSource,
  harnessFromClientName,
  harnessFromUserAgent,
  harnessLabel,
  harnessSourceLabel,
  IDENTITY_HEADERS,
  IDENTITY_META_PREFIXES,
  INJECTED_ENV_HARNESSES,
  isKnownHarness,
  type KnownHarness,
  META_HEADER_PREFIX,
  META_MAX_KEY_LENGTH,
  META_MAX_KEYS,
  META_MAX_TOTAL_BYTES,
  META_MAX_VALUE_BYTES,
  metricHarness,
  normalizeHarness,
  OTHER_HARNESS,
  RESERVED_META_NAMES,
  sanitizeHarnessSlug,
  UNKNOWN_HARNESS,
  USER_AGENT_PATTERNS,
} from './harness/index.ts';
export {
  ACTIVITY_BUCKET_MAX_MS,
  ACTIVITY_BUCKET_MIN_MS,
  ACTIVITY_DEFAULT_WINDOW_MS,
  ACTIVITY_MAX_BUCKETS,
  ActivityBucket,
  ActivityGroupBy,
  ActivityQuery,
  ActivityResponse,
  ActivitySummary,
  API_PREFIX,
  ApiTokenList,
  ApiTokenSummary,
  AppliedQuery,
  ArchivedFilter,
  ArchiveSessionResponse,
  AttentionDecision,
  AttentionPage,
  AttentionQuery,
  AttentionSortKey,
  AuthPrincipal,
  AuthSessionIdPrefixParams,
  AuthSessionInfo,
  AuthSessionList,
  AuthSessionSummary,
  BEARER_TOKEN_RE,
  BlockedAttemptsPage,
  BlockedAttemptsQuery,
  BlockedRequestRow,
  BlockedSortKey,
  BlocklistOverview,
  BlocklistOverviewQuery,
  BlocklistPattern,
  BlocklistSkippedLine,
  BlocklistStats,
  BootPhase,
  BULK_REQUESTS_MAX,
  BULK_SESSIONS_MAX,
  BulkAttentionRequest,
  BulkItemError,
  BulkRequestResult,
  BulkRequestsResponse,
  BulkSessionAction,
  BulkSessionResult,
  BulkSessionsRequest,
  BulkSessionsResponse,
  BulkVaultConfirmRequest,
  Bytes,
  ChangePasswordRequest,
  ChangePasswordResponse,
  ClientErrorReport,
  Count,
  CreateGrantRequest,
  CreateGrantResponse,
  CreateTokenRequest,
  CreateTokenResponse,
  CredentialIdParams,
  CURSOR_MAX_LENGTH,
  Cursor,
  csv,
  DeleteSessionResponse,
  DeleteVaultBindingResponse,
  DomainCount,
  DurationMs,
  Engine,
  EpochMs,
  EXPORT_MEDIA_TYPES,
  Facet,
  FleetPageRow,
  FleetToolCallRow,
  findEndpoint,
  GrantQuery,
  GrantRoute,
  GroupIdParams,
  HandleParams,
  HarnessConflict,
  HarnessMetricRow,
  HarnessMetricsQuery,
  HarnessMetricsResponse,
  HarnessSlug,
  HealthCheckState,
  HealthResponse,
  HealthStatus,
  HTTP_ENDPOINTS,
  type HttpEndpoint,
  type HttpMethod,
  IdempotencyKey,
  IfMatchVersion,
  ImportVaultQuery,
  ImportVaultResponse,
  InputRejectionCode,
  LIMIT_DEFAULT,
  LIMIT_MAX,
  LOG_LEVEL_SPEC_RE,
  LOGS_LIMIT_MAX,
  LockVaultResponse,
  LoginRequest,
  LoginResponse,
  LogoutResponse,
  LogRecord,
  LogsExportQuery,
  LogsPage,
  LogsQuery,
  LogTransport,
  limitQuery,
  listQuery,
  MCP_CONNECTIONS_LIMIT_DEFAULT,
  MCP_CONNECTIONS_LIMIT_MAX,
  McpConnectionRow,
  McpConnectionsQuery,
  McpConnectionsResponse,
  MeResponse,
  MigrationRow,
  Notification,
  NotificationAckResponse,
  NotificationIdParams,
  NotificationsPage,
  NotificationsQuery,
  NotificationsUpdatedResponse,
  OkResponse,
  OPERATOR_MESSAGE_MAX,
  OperatorRequestRow,
  OriginCheck,
  PASSWORD_CHANGE_ALLOWED_OPERATIONS,
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  type Page,
  PageDomainsQuery,
  PageDomainsResponse,
  PageInfo,
  PageQuery,
  PageRow,
  PageSortKey,
  PagesPage,
  PagesQuery,
  PREFERENCES_MAX_BYTES,
  Preferences,
  PreferencesResponse,
  PutGroupPolicyRequest,
  PutGroupPolicyResponse,
  PutPreferencesRequest,
  PutPreferencesResponse,
  PutVaultBindingRequest,
  PutVaultBindingResponse,
  page,
  QueryBool,
  QueryEpochMs,
  QueryInt,
  QueryText,
  REDACTED,
  RealtimeConnection,
  RecentPagesQuery,
  RecentPagesResponse,
  ReloadBlocklistResponse,
  RequestIdParams,
  ResolveAttentionRequest,
  ResolveBindingsRequest,
  ResolveBindingsResponse,
  ResolveRequestResponse,
  ResolveVaultConfirmRequest,
  ResponseMeta,
  RetentionStatus,
  RevealDataDirResponse,
  RevealFailureReason,
  RevokeAllSessionsResponse,
  SavedView,
  SCREENSHOT_CACHE_CONTROL,
  ScreenshotKind,
  ScreenshotRow,
  ScreenshotSortKey,
  ScreenshotsPage,
  SESSION_EXPORT_MAX_ROWS,
  SearchQuery,
  SearchResponse,
  SerializedError,
  SessionAttentionPage,
  SessionAttentionQuery,
  SessionClient,
  SessionCounts,
  SessionDataDir,
  SessionDetail,
  SessionEventParams,
  SessionExportQuery,
  SessionFacets,
  SessionIdParams,
  SessionInputRequest,
  SessionInputResponse,
  SessionPagesPage,
  SessionPagesQuery,
  SessionScreenshotsQuery,
  SessionSortKey,
  SessionSummary,
  SessionsPage,
  SessionsQuery,
  SessionToolCallsPage,
  SessionToolCallsQuery,
  SessionTraceInfo,
  SessionTraceSummary,
  SessionView,
  SetLogLevelRequest,
  SetLogLevelResponse,
  SetViewportRequest,
  SetViewportResponse,
  SortDir,
  StorageStatus,
  SyncVaultResponse,
  SystemCapacity,
  SystemConfigKey,
  SystemConfigRef,
  SystemConfigResponse,
  SystemEvent,
  SystemEventsPage,
  SystemEventsQuery,
  SystemInfo,
  SystemRealtimeResponse,
  sortable,
  TerminateSessionResponse,
  TimelineItem,
  TimelineKind,
  TimelinePage,
  TimelineQuery,
  TimeWindow,
  TokenOwnerKind,
  ToolCallDetail,
  ToolCallRow,
  ToolCallSortKey,
  ToolCallsPage,
  ToolCallsQuery,
  ToolMetricRow,
  ToolMetricsGroupBy,
  ToolMetricsQuery,
  ToolMetricsResponse,
  TraceUnavailableDetails,
  UNGROUPED_GROUP_KEY,
  UnlockVaultRequest,
  UnlockVaultResponse,
  VAULT_EXPORT_VERSION,
  VAULT_HANDLE_RE,
  VaultAccessMode,
  VaultAccessResult,
  VaultAccessRow,
  VaultBinding,
  VaultBindingExport,
  VaultBindingsPage,
  VaultBindingsQuery,
  VaultCapabilities,
  VaultConfirmDecision,
  VaultConfirmPage,
  VaultConfirmQuery,
  VaultExportDocument,
  VaultGroup,
  VaultGrouping,
  VaultGroupPolicy,
  VaultGroupPolicyExport,
  VaultGroupsResponse,
  VaultHandle,
  VaultItem,
  VaultItemsPage,
  VaultItemsQuery,
  VaultLogPage,
  VaultLogQuery,
  VaultLogSortKey,
  VaultOverview,
  VaultStatus,
  VaultUnlockDescriptor,
  VaultUnlockMode,
  VIEWPORT_MAX,
  VIEWPORT_MIN,
  ViewportDimension,
  windowQuery,
} from './http/index.ts';
export {
  CONNECTION_ID_RE,
  ConnectionId,
  EVENT_ID_RE,
  EventId,
  ID_ALPHABET,
  isValidSlug,
  MCP_SESSION_ID_RE,
  McpSessionId,
  NANOID_ALPHABET,
  NOTIFICATION_ID_RE,
  NotificationId,
  OPERATOR_REQUEST_ID_RE,
  OperatorRequestId,
  PRINCIPAL_ID_RE,
  PrincipalId,
  parseSessionId,
  SESSION_ID_RE,
  SESSION_ID_SUFFIX_LENGTH,
  SessionId,
  type SessionIdComponents,
  SLUG_RE,
  TAB_ID_RE,
  TAB_ID_SUFFIX_LENGTH,
  TabId,
  ULID_RE,
} from './ids/index.ts';
export {
  ALL_TOOL_NAMES,
  AppliedIdentity,
  AttentionOutcome,
  AUTH_NAME_RE,
  AvailableVaultEntry,
  BASE_LAUNCH_DEFAULTS,
  BrowserContextOptions,
  Cookie,
  CookieInput,
  defineTool,
  EMPTY_INPUT_JSON_SCHEMA,
  isToolName,
  LaunchOptions,
  type LaunchSessionDefaults,
  launchSessionInput,
  requestAttentionDescription,
  requestAttentionFloorNote,
  SavedAuthEntry,
  SavedAuthResult,
  Selector,
  SessionMetadata,
  TabSummary,
  Timeout,
  TOOL_CONTRACTS,
  TOOL_PACKS,
  type ToolAnnotations,
  type ToolArgs,
  type ToolContract,
  type ToolContractOf,
  type ToolInputSchema,
  type ToolJsonSchema,
  type ToolName,
  ToolNameSchema,
  ToolPackId,
  type ToolResult,
  toolInputJsonSchema,
  toolOutputJsonSchema,
  VaultFillResult,
  VaultFillStatus,
  VaultListResult,
  VaultListScope,
  WaitUntil,
} from './tools/index.ts';
export {
  AttentionCreatedEvent,
  AttentionResolvedEvent,
  BlocklistHitEvent,
  BlocklistReloadedEvent,
  HelloReply,
  InputCommand,
  InputModifiers,
  KeyInput,
  LIVE_INPUT_BATCH_MAX,
  LiveInput,
  LogRecordEvent,
  LogsTailCommand,
  MouseInput,
  NotificationCreatedEvent,
  NotificationUpdatedEvent,
  OkReply,
  PageVisitedEvent,
  type ParsedTopic,
  PingCommand,
  PongReply,
  parseTopic,
  ResyncRequiredReply,
  RetentionCompletedEvent,
  readScreencastHeader,
  SCREENCAST_HEADER_BYTES,
  SCREENCAST_HEADER_LAYOUT,
  SCREENCAST_MAGIC,
  SCREENCAST_MAX_DIMENSION,
  SCREENCAST_QUALITY,
  SCREENCAST_TOPIC_RE,
  ScreencastControl,
  ScreencastFailedPayload,
  ScreencastFrameHeader,
  ScreencastMetaPayload,
  ScreencastSetSizeCommand,
  ScreencastStartCommand,
  ScreencastStartedPayload,
  ScreencastStartedReply,
  ScreencastStopCommand,
  ScreencastStoppedPayload,
  ScreenshotCapturedEvent,
  SESSION_TOPIC_RE,
  SessionClosedEvent,
  SessionOpenedEvent,
  SessionRemovedEvent,
  SessionUpdatedEvent,
  SessionWarningEvent,
  SetViewportCommand,
  SubscribeCommand,
  SubscribedReply,
  SystemCapacityEvent,
  SystemDegradedEvent,
  SystemRecoveredEvent,
  SystemTickEvent,
  screencastTopic,
  sessionTopic,
  ToolCalledEvent,
  TouchInput,
  TouchPoint,
  UnsubscribeCommand,
  UnsubscribedReply,
  VaultAccessEvent,
  VaultBindingChangedEvent,
  VaultConfirmCreatedEvent,
  VaultConfirmResolvedEvent,
  VaultLockStateEvent,
  VaultPolicyChangedEvent,
  WS_CLOSE,
  WS_COMMAND_SCOPES,
  WS_LIMITS,
  WS_PATH,
  WS_PROTOCOL_VERSION,
  WS_SESSION_TOPIC_EVENTS,
  WS_STATIC_TOPICS,
  WS_SUBPROTOCOL,
  WS_TOPIC_EVENTS,
  WS_TOPIC_SCOPES,
  WsClientCommand,
  type WsCommandType,
  WsCorr,
  WsEnvelope,
  WsErrorMessage,
  WsEventMessage,
  WsFeedEvent,
  type WsFeedEventType,
  WsKind,
  WsReplyMessage,
  WsReplyPayload,
  WsSeq,
  WsServerMessage,
  WsStaticTopic,
  WsStreamMessage,
  WsTopic,
  writeScreencastHeader,
  wsEnvelope,
} from './ws/index.ts';
