/** @module contracts/notifications — the notification contract (D-32): `NotificationMessage`, its taxonomy, channel rules and the published JSON Schema */

export {
  ANOMALY_DEFAULTS,
  AnomalyRule,
  DEFAULT_CONTENT_LEVEL,
  DEFAULT_DIGEST_AT,
  DigestRule,
  isValidTimeZone,
  NotificationChannelName,
  NotificationChannelRules,
  NotificationChannelSecretRefs,
  NotificationChannelTarget,
  QuietHours,
  RESERVED_ENV_PREFIX,
  SecretEnvName,
  StartupNotificationChannel,
  SUPPRESSION_REASONS,
  type SuppressionReason,
  WEEKDAYS,
  Weekday,
} from './channel.ts';
export { NOTIFICATION_MESSAGE_SCHEMA_ID, notificationMessageJsonSchema } from './json-schema.ts';
export {
  ActAction,
  ActionStyle,
  Block,
  type BlockType,
  ChartBlock,
  CodeBlock,
  DashboardPath,
  DividerBlock,
  FieldsBlock,
  FooterBlock,
  HeadingBlock,
  ImageBlock,
  Inline,
  InlineBold,
  InlineCode,
  InlineItalic,
  InlineLink,
  InlineRun,
  InlineText,
  InlineTime,
  ListBlock,
  NOTIFICATION_ACTIONS_MAX,
  NOTIFICATION_BLOCKS_MAX,
  NOTIFICATION_CHART_POINTS_MAX,
  NOTIFICATION_LABEL_MAX,
  NOTIFICATION_SCHEMA_VERSION,
  NOTIFICATION_SUMMARY_MAX,
  NOTIFICATION_TEXT_MAX,
  NOTIFICATION_TITLE_MAX,
  NotificationAction,
  NotificationCommand,
  NotificationEntities,
  NotificationMessage,
  NotificationPrivacy,
  NotificationReport,
  OpenAction,
  QuoteBlock,
  TableBlock,
  TextBlock,
} from './message.ts';
export {
  ACTION_OUTCOME_TEXT,
  ACTION_PAYLOAD_RE,
  ACTION_TOKEN_LENGTH,
  ACTION_TOKEN_PREFIX,
  ACTION_TOKEN_TTL_MS,
  ANOMALY_CHECK_TEXT,
  ANOMALY_CHECKS,
  type AnomalyCheck,
  AVAILABLE_CHANNEL_KINDS,
  AVAILABLE_DISCORD_MODES,
  AvailableChannelKind,
  CHANNEL_KIND_SPECS,
  CHANNEL_PRESETS,
  type ChannelConfigProblem,
  type ChannelKindSpec,
  checkChannelConfig,
  checkChannelRules,
  DELIVERY_REASON_TEXT,
  DISCORD_BOT_PERMISSIONS,
  DISCORD_MODES,
  deliveryReasonText,
  discordInviteUrl,
  hasPresserIdentity,
  looksLikeSecretValue,
  NTFY_DEFAULT_SERVER,
  PREVIEW_SAMPLE_LABEL,
  PREVIEW_SAMPLES,
  PreviewSample,
  type SecretParamSpec,
  supportsActButtons,
  type TargetKeySpec,
  TELEGRAM_DELETE_WINDOW_MS,
  TELEGRAM_TTL_MAX_MS,
} from './platforms.ts';
export {
  classifyLegacy,
  IN_APP_ONLY_KINDS,
  KIND_CATEGORY,
  KIND_LABEL,
  KIND_SEVERITY,
  KIND_TYPE,
  type LegacyClassification,
  type LegacyNotificationFacts,
  SESSION_CRASHED_TITLE,
} from './taxonomy.ts';
