/** @module contracts/notifications — the notification contract (D-32): `NotificationMessage`, its taxonomy, channel rules and the published JSON Schema */

export {
  DEFAULT_CONTENT_LEVEL,
  NotificationChannelName,
  NotificationChannelRules,
  NotificationChannelSecretRefs,
  NotificationChannelTarget,
  QuietHours,
  RESERVED_ENV_PREFIX,
  SecretEnvName,
  StartupNotificationChannel,
  SUPPRESSION_REASONS,
  type SuppressionReason,
} from './channel.ts';
export { NOTIFICATION_MESSAGE_SCHEMA_ID, notificationMessageJsonSchema } from './json-schema.ts';
export {
  ActAction,
  ActionStyle,
  Block,
  type BlockType,
  CodeBlock,
  DashboardPath,
  DividerBlock,
  FieldsBlock,
  FooterBlock,
  HeadingBlock,
  ImageBlock,
  Inline,
  InlineBold,
  InlineCode,
  InlineItalic,
  InlineLink,
  InlineRun,
  InlineText,
  InlineTime,
  ListBlock,
  NOTIFICATION_ACTIONS_MAX,
  NOTIFICATION_BLOCKS_MAX,
  NOTIFICATION_LABEL_MAX,
  NOTIFICATION_SCHEMA_VERSION,
  NOTIFICATION_SUMMARY_MAX,
  NOTIFICATION_TEXT_MAX,
  NOTIFICATION_TITLE_MAX,
  NotificationAction,
  NotificationCommand,
  NotificationEntities,
  NotificationMessage,
  NotificationPrivacy,
  OpenAction,
  QuoteBlock,
  TableBlock,
  TextBlock,
} from './message.ts';
export {
  classifyLegacy,
  IN_APP_ONLY_KINDS,
  KIND_CATEGORY,
  KIND_LABEL,
  KIND_SEVERITY,
  KIND_TYPE,
  type LegacyClassification,
  type LegacyNotificationFacts,
  SESSION_CRASHED_TITLE,
} from './taxonomy.ts';
