/** @module contracts/ws — realtime protocol v1: envelope, topics, commands, messages, feed events, screencast (D-10) */

export type { WsCommandType } from './commands.ts';
export {
  InputCommand,
  LogsTailCommand,
  PingCommand,
  SCREENCAST_MAX_DIMENSION,
  SCREENCAST_QUALITY,
  ScreencastSetSizeCommand,
  ScreencastStartCommand,
  ScreencastStopCommand,
  SetViewportCommand,
  SubscribeCommand,
  UnsubscribeCommand,
  WS_COMMAND_SCOPES,
  WS_TOPIC_SCOPES,
  WsClientCommand,
} from './commands.ts';
export {
  WS_CLOSE,
  WS_LIMITS,
  WS_PATH,
  WS_PROTOCOL_VERSION,
  WS_SUBPROTOCOL,
  WsCorr,
  WsEnvelope,
  WsKind,
  WsSeq,
  wsEnvelope,
} from './envelope.ts';
export type { WsFeedEventType } from './feed-events.ts';
export {
  AttentionCreatedEvent,
  AttentionResolvedEvent,
  BlocklistHitEvent,
  BlocklistReloadedEvent,
  LogRecordEvent,
  NotificationCreatedEvent,
  NotificationUpdatedEvent,
  PageVisitedEvent,
  RetentionCompletedEvent,
  ScreenshotCapturedEvent,
  SessionClosedEvent,
  SessionOpenedEvent,
  SessionRemovedEvent,
  SessionUpdatedEvent,
  SessionWarningEvent,
  SystemCapacityEvent,
  SystemDegradedEvent,
  SystemRecoveredEvent,
  SystemTickEvent,
  ToolCalledEvent,
  VaultAccessEvent,
  VaultBindingChangedEvent,
  VaultConfirmCreatedEvent,
  VaultConfirmResolvedEvent,
  VaultLockStateEvent,
  VaultPolicyChangedEvent,
  WS_SESSION_TOPIC_EVENTS,
  WS_TOPIC_EVENTS,
  WsFeedEvent,
} from './feed-events.ts';
export {
  InputModifiers,
  KeyInput,
  LIVE_INPUT_BATCH_MAX,
  LiveInput,
  MouseInput,
  TouchInput,
  TouchPoint,
} from './live-input.ts';
export {
  HelloReply,
  OkReply,
  PongReply,
  ResyncRequiredReply,
  ScreencastStartedReply,
  SubscribedReply,
  UnsubscribedReply,
  WsErrorMessage,
  WsErrorPayload,
  WsEventMessage,
  WsReplyMessage,
  WsReplyPayload,
  WsServerMessage,
  WsStreamMessage,
} from './messages.ts';
export {
  readScreencastHeader,
  SCREENCAST_HEADER_BYTES,
  SCREENCAST_HEADER_LAYOUT,
  SCREENCAST_MAGIC,
  ScreencastControl,
  ScreencastFailedPayload,
  ScreencastFrameHeader,
  ScreencastMetaPayload,
  ScreencastStartedPayload,
  ScreencastStoppedPayload,
  writeScreencastHeader,
} from './screencast.ts';
export type { ParsedTopic } from './topics.ts';
export {
  parseTopic,
  SCREENCAST_TOPIC_RE,
  SESSION_TOPIC_RE,
  screencastTopic,
  sessionTopic,
  WS_STATIC_TOPICS,
  WsStaticTopic,
  WsTopic,
} from './topics.ts';
