import { describe, expect, it } from 'bun:test';
import {
  type DocsVersion,
  frontmatter,
  pageId,
  pageRoute,
  resolveVersions,
  rewriteLinks,
  rewriteTarget,
  sidebarFromReadme,
  splitPage,
} from './docs-source.ts';

const latest: DocsVersion = {
  major: 1,
  label: 'v1',
  latest: true,
  base: '/docs/',
  ref: 'main',
  version: '1.2.0',
};
const v0: DocsVersion = {
  major: 0,
  label: 'v0',
  latest: false,
  base: '/docs/v0/',
  ref: 'browserhive@0.9.3',
  version: '0.9.3',
};
const published = new Set([
  'README.md',
  'guide/cli.md',
  'guide/vault.md',
  'reference/tools.md',
  'reference/config.schema.json',
]);

describe('resolveVersions', () => {
  it('uses the working tree for the current major and the newest stable tag for older majors', () => {
    const versions = resolveVersions('2.0.1', [
      'browserhive@0.1.0',
      'browserhive@0.10.2',
      'browserhive@0.9.9',
      'browserhive@1.4.0',
      'browserhive@1.4.1-beta.1',
      'browserhive@2.0.0',
      'other@9.9.9',
    ]);
    expect(versions.map((v) => [v.label, v.base, v.ref, v.latest])).toEqual([
      ['v2', '/docs/', 'main', true],
      ['v1', '/docs/v1/', 'browserhive@1.4.0', false],
      ['v0', '/docs/v0/', 'browserhive@0.10.2', false],
    ]);
  });

  it('has a single latest version before any release', () => {
    expect(resolveVersions('0.1.0', [])).toHaveLength(1);
  });
});

describe('pages', () => {
  it('maps README files to index routes', () => {
    expect(pageId('README.md')).toBe('index');
    expect(pageId('guide/README.md')).toBe('guide/index');
    expect(pageId('guide/cli.md')).toBe('guide/cli');
    expect(pageRoute('/docs/v0/', 'index')).toBe('/docs/v0/');
    expect(pageRoute('/docs/', 'guide/index')).toBe('/docs/guide/');
    expect(pageRoute('/docs/', 'guide/cli')).toBe('/docs/guide/cli/');
  });

  it('takes the title from the H1, skipping the generated banner', () => {
    const page = splitPage(
      '<!-- generated by x; do not edit -->\n\n# MCP tools\n\nThe **43** tools, see [errors](errors.md).\n',
      'tools',
    );
    expect(page.title).toBe('MCP tools');
    expect(page.generated).toBe(true);
    expect(page.body.startsWith('The **43**')).toBe(true);
    expect(page.description).toBe('The 43 tools, see errors.');
  });
});

describe('links', () => {
  const ctx = { docsPath: 'guide/cli.md', version: v0, published };

  it('rewrites page links to routes in the same version, keeping anchors', () => {
    expect(rewriteTarget('vault.md#bindings', ctx)).toBe('/docs/v0/guide/vault/#bindings');
    expect(rewriteTarget('../reference/tools.md', ctx)).toBe('/docs/v0/reference/tools/');
    expect(rewriteTarget('../README.md', { ...ctx, version: latest })).toBe('/docs/');
  });

  it('serves published assets and sends everything else to GitHub at the version ref', () => {
    expect(rewriteTarget('../reference/config.schema.json', ctx)).toBe(
      '/docs/v0/reference/config.schema.json',
    );
    expect(rewriteTarget('../../SECURITY.md', ctx)).toBe(
      'https://github.com/arg1998/BrowserHive/blob/browserhive@0.9.3/SECURITY.md',
    );
    expect(rewriteTarget('../contributing/architecture.md', ctx)).toBe(
      'https://github.com/arg1998/BrowserHive/blob/browserhive@0.9.3/docs/contributing/architecture.md',
    );
  });

  it('leaves absolute links, anchors and code blocks alone', () => {
    const md = [
      '[a](https://x.dev) [b](#top) [c](vault.md)',
      '```md',
      '[d](vault.md)',
      '```',
      '[e](vault.md "t")',
    ].join('\n');
    expect(rewriteLinks(md, ctx)).toBe(
      [
        '[a](https://x.dev) [b](#top) [c](/docs/v0/guide/vault/)',
        '```md',
        '[d](vault.md)',
        '```',
        '[e](/docs/v0/guide/vault/ "t")',
      ].join('\n'),
    );
  });
});

describe('sidebarFromReadme', () => {
  it('builds groups from README sections and drops contributing and non-page links', () => {
    const readme = [
      '# Docs',
      '## Get started',
      '- [CLI](guide/cli.md): commands',
      '## Reference',
      '- [Tools](reference/tools.md)',
      '- [Schema](reference/config.schema.json)',
      '## Contributing',
      '- [Architecture](contributing/architecture.md)',
    ].join('\n');
    expect(sidebarFromReadme(readme, { version: latest, published })).toEqual([
      { label: 'Get started', items: [{ label: 'CLI', link: '/docs/guide/cli/' }] },
      { label: 'Reference', items: [{ label: 'Tools', link: '/docs/reference/tools/' }] },
    ]);
  });
});

describe('frontmatter', () => {
  it('writes JSON values and bare timestamps', () => {
    expect(
      frontmatter({ title: 'A: "b"', editUrl: false, skip: undefined, lastUpdated: new Date(0) }),
    ).toBe(
      '---\ntitle: "A: \\"b\\""\neditUrl: false\nlastUpdated: 1970-01-01T00:00:00.000Z\n---\n\n',
    );
  });
});
