/** @module scripts/gen-docs/markdown — Markdown and JSON Schema rendering helpers shared by the reference generators */

/** First line of every generated Markdown file (spec 05 §9). */
export const GENERATED_HEADER = '<!-- generated by scripts/gen-docs.ts; do not edit -->';

/** Values of `Number.MAX_SAFE_INTEGER` and above are zod's "no bound" sentinels and are not rendered. */
const UNBOUNDED = Number.MAX_SAFE_INTEGER;

/**
 * Whether a value is a plain JSON object.
 *
 * @returns `true` for non-null, non-array objects.
 */
export function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * Wrap text in a code span whose fence is longer than any backtick run inside it.
 *
 * @returns The inline code span.
 */
export function inlineCode(text: string): string {
  const runs = text.match(/`+/g) ?? [];
  const longest = runs.reduce((max, run) => Math.max(max, run.length), 0);
  const fence = '`'.repeat(longest + 1);
  const pad = text.startsWith('`') || text.endsWith('`') ? ' ' : '';
  return `${fence}${pad}${text}${pad}${fence}`;
}

function escapeCell(text: string): string {
  return text.replace(/\r?\n/g, ' ').replace(/\|/g, '\\|');
}

/**
 * Render a GitHub-flavoured Markdown table; cells are escaped (pipes, newlines).
 *
 * @returns The table text without a trailing newline.
 */
export function table(headers: readonly string[], rows: readonly (readonly string[])[]): string {
  const head = `| ${headers.map(escapeCell).join(' | ')} |`;
  const rule = `|${headers.map(() => '---').join('|')}|`;
  const body = rows.map((row) => `| ${row.map((cell) => escapeCell(cell)).join(' | ')} |`);
  return [head, rule, ...body].join('\n');
}

/**
 * An explicit HTML anchor so links can target exact ids (error codes, key names, tool names).
 *
 * @returns `<a id="…"></a>`.
 */
export function anchor(id: string): string {
  return `<a id="${id}"></a>`;
}

/**
 * Join document blocks with one blank line and end with a single newline.
 *
 * @returns The document text.
 */
export function document(blocks: readonly string[]): string {
  return `${blocks.filter((b) => b.length > 0).join('\n\n')}\n`;
}

/**
 * Render a JSON value compactly for a table cell or prose.
 *
 * @returns The value as inline code.
 */
export function jsonValue(value: unknown): string {
  return inlineCode(JSON.stringify(value) ?? 'undefined');
}

function primitiveName(type: unknown): string {
  return typeof type === 'string' ? inlineCode(type) : inlineCode('any');
}

function unique(items: readonly string[]): string[] {
  return [...new Set(items)];
}

/**
 * Human type of a JSON Schema node (`string`, one of `a`, `b`, `object[]`, `string` or `null`…).
 *
 * @returns Markdown text.
 */
export function describeType(schema: unknown): string {
  if (!isRecord(schema)) return inlineCode('any');
  if ('const' in schema) return inlineCode(JSON.stringify(schema['const']) ?? 'null');
  if (typeof schema['$ref'] === 'string') return inlineCode('object');
  const enumValues = schema['enum'];
  if (Array.isArray(enumValues)) {
    return `one of ${enumValues.map((v) => inlineCode(String(v))).join(', ')}`;
  }
  const variants = schema['anyOf'] ?? schema['oneOf'];
  if (Array.isArray(variants)) return unique(variants.map(describeType)).join(' or ');
  const type = schema['type'];
  if (Array.isArray(type)) return unique(type.map(primitiveName)).join(' or ');
  if (type === 'array') {
    const items = schema['items'];
    if (isRecord(items) && items['type'] === 'object') return inlineCode('object[]');
    if (isRecord(items) && typeof items['type'] === 'string' && !('enum' in items)) {
      return inlineCode(`${items['type']}[]`);
    }
    return `array of ${describeType(items)}`;
  }
  if (typeof type === 'string') return inlineCode(type);
  return inlineCode('any');
}

/**
 * Validation constraints of a JSON Schema node as short phrases (pattern, lengths, bounds, keys).
 *
 * @returns The phrases, possibly empty.
 */
export function describeConstraints(schema: unknown): string[] {
  if (!isRecord(schema)) return [];
  const out: string[] = [];
  const num = (key: string): number | undefined => {
    const v = schema[key];
    return typeof v === 'number' && Math.abs(v) < UNBOUNDED ? v : undefined;
  };
  if (typeof schema['pattern'] === 'string') out.push(`pattern ${inlineCode(schema['pattern'])}`);
  const minLength = num('minLength');
  if (minLength !== undefined) out.push(`min length ${minLength}`);
  const maxLength = num('maxLength');
  if (maxLength !== undefined) out.push(`max length ${maxLength}`);
  const minimum = num('minimum');
  if (minimum !== undefined) out.push(`≥ ${minimum}`);
  const maximum = num('maximum');
  if (maximum !== undefined) out.push(`≤ ${maximum}`);
  const minItems = num('minItems');
  if (minItems !== undefined) out.push(`at least ${minItems} item${minItems === 1 ? '' : 's'}`);
  const maxItems = num('maxItems');
  if (maxItems !== undefined) out.push(`at most ${maxItems} items`);
  const properties = schema['properties'];
  if (isRecord(properties) && Object.keys(properties).length > 0) {
    out.push(`keys ${Object.keys(properties).map(inlineCode).join(', ')}`);
  }
  if (schema['type'] === 'object' && isRecord(schema['additionalProperties'])) {
    out.push('additional keys allowed');
  }
  const items = schema['items'];
  if (isRecord(items)) {
    const inner = describeConstraints(items);
    if (inner.length > 0) out.push(`each item: ${inner.join(', ')}`);
  }
  return out;
}

/** One row of an object schema's field listing. */
export interface FieldRow {
  readonly name: string;
  readonly schema: unknown;
  readonly required: boolean;
}

/**
 * The top-level fields of an object JSON Schema, in declaration order.
 *
 * @returns The fields; empty when the node is not an object schema.
 */
export function objectFields(schema: unknown): FieldRow[] {
  if (!isRecord(schema)) return [];
  const properties = schema['properties'];
  if (!isRecord(properties)) return [];
  const requiredList = schema['required'];
  const required = new Set(Array.isArray(requiredList) ? requiredList.map(String) : []);
  return Object.entries(properties).map(([name, node]) => ({
    name,
    schema: node,
    required: required.has(name),
  }));
}
