/** @module lib/icons — typed alias map over lucide-react (16px in controls and rows, 20px in nav), the only icon vocabulary of the dashboard */
import {
  Activity,
  AppWindow,
  Archive,
  ArrowDown,
  ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  Bell,
  BellOff,
  BookOpen,
  Braces,
  Bug,
  Camera,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleQuestionMark,
  CircleX,
  Clock,
  Code,
  Columns3,
  Command,
  Cookie,
  Copy,
  CornerDownLeft,
  createLucideIcon,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileQuestion,
  FileText,
  Folder,
  Globe,
  Hand,
  Hash,
  Hourglass,
  House,
  Image,
  Inbox,
  Info,
  Keyboard,
  KeyRound,
  Laptop,
  Layers,
  LayoutDashboard,
  Link,
  List,
  ListChecks,
  ListFilter,
  LoaderCircle,
  Lock,
  LogOut,
  type LucideIcon,
  Maximize,
  Menu,
  Minimize,
  Minus,
  Monitor,
  MonitorPlay,
  Moon,
  MousePointer,
  MousePointerClick,
  Move,
  OctagonAlert,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  Pause,
  Pencil,
  Play,
  Plus,
  Pointer,
  Power,
  Proportions,
  RefreshCw,
  Rocket,
  RotateCw,
  Rows3,
  Rows4,
  Save,
  ScreenShare,
  ScrollText,
  Search,
  Settings2,
  ShieldBan,
  Square,
  Sun,
  Table2,
  Terminal,
  TextCursorInput,
  Trash,
  TriangleAlert,
  Undo2,
  Upload,
  UserRound,
  Vault,
  Volume2,
  VolumeX,
  Wifi,
  WifiOff,
  Wrench,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';

/** The GitHub mark in lucide's stroke style (lucide no longer ships brand icons). */
const GitHub = createLucideIcon('github', [
  [
    'path',
    {
      d: 'M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4',
      key: 'github-body',
    },
  ],
  ['path', { d: 'M9 18c-4.51 2-5-2-7-2', key: 'github-tail' }],
]);

/** Icon sizes (px): 14 inline in dense text, 16 in controls and rows, 20 in nav. */
export const ICON_SIZE = { sm: 14, md: 16, lg: 20 } as const;
/** Icon size name. */
export type IconSize = keyof typeof ICON_SIZE;

/** Semantic icon names → lucide components. Add here, never import lucide in a feature. */
export const ICONS = {
  overview: LayoutDashboard,
  sessions: MonitorPlay,
  websites: Globe,
  blocklist: ShieldBan,
  attention: Hand,
  vault: Vault,
  vaultLog: ScrollText,
  logs: Terminal,
  system: Settings2,
  notifications: Bell,
  notificationsOff: BellOff,
  search: Search,
  command: Command,
  keyboard: Keyboard,
  theme: Laptop,
  sun: Sun,
  moon: Moon,
  copy: Copy,
  check: Check,
  checkAll: CheckCheck,
  close: X,
  menu: Menu,
  sidebar: PanelLeft,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  first: ChevronsLeft,
  last: ChevronsRight,
  sortAsc: ArrowUp,
  sortDesc: ArrowDown,
  sortNone: ArrowUpDown,
  columns: Columns3,
  more: Ellipsis,
  spinner: LoaderCircle,
  warn: TriangleAlert,
  danger: OctagonAlert,
  info: Info,
  error: CircleAlert,
  help: CircleQuestionMark,
  book: BookOpen,
  github: GitHub,
  rocket: Rocket,
  lock: Lock,
  logout: LogOut,
  user: UserRound,
  show: Eye,
  hide: EyeOff,
  online: Wifi,
  offline: WifiOff,
  refresh: RefreshCw,
  external: ExternalLink,
  link: Link,
  delete: Trash,
  archive: Archive,
  play: Play,
  stop: Square,
  expand: Maximize,
  collapse: Minimize,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  activity: Activity,
  layers: Layers,
  inbox: Inbox,
  globe: Globe,
  ip: Hash,
  local: House,
  ftp: Folder,
  other: Link,
  lifecycle: Zap,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  bug: Bug,
  success: CircleCheck,
  failure: CircleX,
  notFound: FileQuestion,
  filter: ListFilter,
  monitor: Monitor,
  densityComfortable: Rows3,
  densityCompact: Rows4,
  minus: Minus,
  enter: CornerDownLeft,
  undo: Undo2,
  clock: Clock,
  sound: Volume2,
  soundOff: VolumeX,
  // Admin pages (B3)
  plus: Plus,
  edit: Pencil,
  // Session workspace (B1)
  pause: Pause,
  image: Image,
  download: Download,
  list: List,
  table: Table2,
  tool: Wrench,
  retry: RotateCw,
  resize: Proportions,
  live: ScreenShare,
  takeover: MousePointerClick,
  json: Braces,
  // Session workspace fixes (lane B): focus-live layout and per-tool activity icons
  focusLive: PanelLeftClose,
  showPanel: PanelLeftOpen,
  toolNavigate: Globe,
  toolClick: MousePointer,
  toolHover: Pointer,
  toolType: TextCursorInput,
  toolKey: Keyboard,
  toolSelect: ListChecks,
  toolScroll: ArrowDownUp,
  toolDrag: Move,
  toolScreenshot: Camera,
  toolContent: FileText,
  toolEvaluate: Code,
  toolCookies: Cookie,
  toolUpload: Upload,
  toolDownload: Download,
  toolWait: Hourglass,
  toolTab: AppWindow,
  toolLaunch: Rocket,
  toolClose: Power,
  toolSave: Save,
  toolVault: KeyRound,
  toolHistory: ArrowLeft,
  toolReload: RotateCw,
  toolViewport: Proportions,
} as const satisfies Record<string, LucideIcon>;

/** Icon name. */
export type IconName = keyof typeof ICONS;

/** Resolve a name to its component. */
export function iconFor(name: IconName): LucideIcon {
  return ICONS[name];
}
