/** @module scripts/gen-db-types — regenerates `packages/core/src/infra/persistence/generated/db.d.ts` from a freshly migrated database (D-04). */

import { rmSync } from 'node:fs';
import { join } from 'node:path';
import { generate, KyselyBunSqliteDialect } from 'kysely-codegen';
import { openDatabase } from '../packages/core/src/infra/persistence/open.ts';

const OUT = join(
  import.meta.dir,
  '..',
  'packages',
  'core',
  'src',
  'infra',
  'persistence',
  'generated',
  'db.d.ts',
);
const check = process.argv.includes('--check');

const silentLogger = {
  child: () => silentLogger,
  isLevelEnabled: () => false,
  error: () => undefined,
  warn: () => undefined,
  info: () => undefined,
  debug: () => undefined,
  trace: () => undefined,
};
const clock = {
  now: () => Date.now(),
  sleep: (ms: number) => new Promise<void>((r) => setTimeout(r, ms)),
};

// kysely-codegen's `--dialect bun-sqlite` (alias of `worker-bun-sqlite`) and `kysely-bun-sqlite`
// both require third-party dialect packages we do not ship; the programmatic API accepts any
// Kysely instance, so we introspect through the owned BunSqliteDialect instead.
const handle = await openDatabase({
  path: ':memory:',
  dataDir: '/nonexistent',
  appVersion: 'codegen',
  clock,
  logger: silentLogger,
});
try {
  if (check) {
    const current = await Bun.file(OUT).text();
    const generated = await generate({
      db: handle.db,
      dialect: new KyselyBunSqliteDialect(),
      outFile: null,
      print: false,
      typeOnlyImports: true,
      skipAutogeneratedFileComment: false,
    });
    if (normalise(generated) !== normalise(current)) {
      console.error('db.d.ts is out of date; run `bun run gen:db-types`');
      process.exit(1);
    }
    console.log('db.d.ts is up to date');
  } else {
    await generate({
      db: handle.db,
      dialect: new KyselyBunSqliteDialect(),
      outFile: OUT,
      typeOnlyImports: true,
    });
    console.log(`wrote ${OUT}`);
  }
} finally {
  await handle.close();
  rmSync('/nonexistent', { force: true, recursive: true });
}

/** Ignores trailing whitespace and the generator's timestamp-free banner differences. */
function normalise(text: string): string {
  return text
    .split('\n')
    .map((line) => line.trimEnd())
    .join('\n')
    .trim();
}
