/** @module scripts/sync-version — writes packages/core/src/version.ts from packages/browserhive/package.json (spec 06 §5). */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = join(import.meta.dir, '..');
const manifestPath = join(root, 'packages/browserhive/package.json');
const manifest: { version?: unknown } = JSON.parse(readFileSync(manifestPath, 'utf8'));
if (
  typeof manifest.version !== 'string' ||
  !/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(manifest.version)
) {
  console.error(`sync-version: invalid version in ${manifestPath}`);
  process.exit(1);
}
const target = join(root, 'packages/core/src/version.ts');
const content = `/** @module core/version — generated by scripts/sync-version.ts; do not edit */\nexport const VERSION = '${manifest.version}' as const;\n`;
const check = process.argv.includes('--check');
let current = '';
try {
  current = readFileSync(target, 'utf8');
} catch {
  current = '';
}
if (check) {
  if (current !== content) {
    console.error(
      'sync-version: packages/core/src/version.ts is stale; run `bun run sync:version`',
    );
    process.exit(1);
  }
  console.log('sync-version: up to date');
} else if (current !== content) {
  writeFileSync(target, content);
  console.log(`sync-version: wrote ${manifest.version}`);
} else {
  console.log('sync-version: unchanged');
}
