/** @module contracts/errors/codes-boot — boot-phase error codes (config, bind, data dir, database); exit codes per spec 08 §7.3 */
import { z } from 'zod';
import { defineError } from './spec.ts';

/** Errors raised before the listener is bound. `httpStatus` is nominal: they are printed by the CLI. */
export const BOOT_ERRORS = {
  ADMIN_REQUIRES_HTTP: defineError({
    code: 'ADMIN_REQUIRES_HTTP',
    httpStatus: 500,
    category: 'boot',
    retryable: 'never',
    title: 'Dashboard requires http',
    message: 'admin=true requires transport=http. The dashboard is not available under stdio.',
    hint: 'Drop admin=true, or use transport=http.',
    details: z.object({}),
    docs: true,
    exitCode: 3,
    cause:
      '`admin=true` was combined with `transport=stdio`; stdio is single-client and cannot host the dashboard.',
    resolution: 'Run with the http transport (the default) to use the dashboard.',
  }),
  INSECURE_BIND_REFUSED: defineError({
    code: 'INSECURE_BIND_REFUSED',
    httpStatus: 500,
    category: 'boot',
    retryable: 'never',
    title: 'Insecure bind refused',
    message:
      'Refusing to bind {host} without authentication. Set auth=token, or set allowInsecureBind=true to accept the risk.',
    hint: 'Set auth=token for LAN exposure.',
    details: z.object({ host: z.string() }),
    docs: true,
    exitCode: 3,
    cause:
      'A non-loopback `host` was requested without `auth=token` and without `allowInsecureBind=true`.',
    resolution: 'Enable token auth, or acknowledge the risk with `allowInsecureBind=true`.',
  }),
  PORT_IN_USE: defineError({
    code: 'PORT_IN_USE',
    httpStatus: 500,
    category: 'boot',
    retryable: 'never',
    title: 'Port in use',
    message: 'Cannot listen on {host}:{port}: the port is already in use ({errno}).',
    hint: 'Pick another port with --port, or stop the process holding it.',
    details: z.object({ host: z.string(), port: z.number().int(), errno: z.string() }),
    docs: true,
    exitCode: 3,
    cause: 'Another process (often a previous BrowserHive) is bound to the same host and port.',
    resolution: 'Stop the other process or choose a free port.',
  }),
  BIND_FAILED: defineError({
    code: 'BIND_FAILED',
    httpStatus: 500,
    category: 'boot',
    retryable: 'never',
    title: 'Bind failed',
    message: 'Cannot listen on {host}:{port} ({errno}).',
    hint: 'Check the address exists on this host and the port is permitted.',
    details: z.object({ host: z.string(), port: z.number().int(), errno: z.string() }),
    docs: true,
    exitCode: 1,
    cause:
      'The listener could not bind for a reason other than a busy port (EACCES, EADDRNOTAVAIL…).',
    resolution: 'Use an address assigned to this host and an unprivileged port.',
  }),
  CONFIG_INVALID: defineError({
    code: 'CONFIG_INVALID',
    httpStatus: 400,
    category: 'boot',
    retryable: 'never',
    title: 'Invalid configuration value',
    message: 'invalid value for {source}: {reason}',
    hint: "Run 'browserhive config validate' to see every problem.",
    details: z.object({ key: z.string(), source: z.string(), reason: z.string() }),
    docs: true,
    exitCode: 64,
    cause: 'A value failed its grammar, range or a cross-field rule.',
    resolution: 'Fix the value at the named source; the grammar is in the message.',
  }),
  CONFIG_UNKNOWN_KEY: defineError({
    code: 'CONFIG_UNKNOWN_KEY',
    httpStatus: 400,
    category: 'boot',
    retryable: 'never',
    title: 'Unknown configuration key',
    message: "unknown key '{key}' in {source}.",
    hint: "Run 'browserhive --help' for the list of keys.",
    details: z.object({ key: z.string(), source: z.string(), suggestion: z.string().optional() }),
    docs: true,
    exitCode: 64,
    cause:
      'A flag, environment variable or config-file key is not in the registry (typo or removed knob).',
    resolution: 'Use the suggested name; kebab-case flag spellings are not supported.',
  }),
  BLOCKLIST_LOAD_FAILED: defineError({
    code: 'BLOCKLIST_LOAD_FAILED',
    httpStatus: 400,
    category: 'boot',
    retryable: 'never',
    title: 'Blocklist could not be loaded',
    message: 'Cannot load blocklist {path}: {reason}',
    hint: 'Check the path and file permissions.',
    details: z.object({ path: z.string(), reason: z.string() }),
    docs: true,
    exitCode: 3,
    cause: 'The configured blocklist file is missing, unreadable or over the entry cap.',
    resolution: 'Fix the file; a configured-but-unreadable blocklist is fatal by design.',
  }),
  SANDBOX_UNAVAILABLE: defineError({
    code: 'SANDBOX_UNAVAILABLE',
    httpStatus: 503,
    category: 'boot',
    retryable: 'never',
    title: 'Sandbox unavailable',
    message: "Channel '{channel}' cannot run with Chromium's sandbox on this host: {reason}",
    hint: "Retrying will not help. Use a browser that can run sandboxed here, or change the sandbox setting; 'browserhive doctor' lists the options for this host.",
    details: z.object({
      channel: z.string(),
      reason: z.string(),
      required_by: z.enum(['config', 'launch_options']),
      executable: z.string().optional(),
      cause: z.string().optional(),
      alternatives: z.array(z.string()),
      guidance: z.array(z.string()),
    }),
    docs: true,
    exitCode: 3,
    cause:
      "The sandbox was required, by `sandbox=on` or by an agent's `launch_options.chromiumSandbox: true`, and the browser could not start with it. Typical hosts: Ubuntu 23.10+ with the bundled browser (AppArmor restricts user namespaces to programs with a profile), running as root (Chrome refuses), Docker's default seccomp profile, or a kernel with unprivileged user namespaces disabled. With `sandbox=on` the server refuses to start (exit code 3); a `launch_session` fails with this code and `retryable: never`. Under `sandbox=auto` it is never raised: the session falls back.",
    resolution:
      'Run `browserhive doctor`: it probes every installed browser and prints the ways out for this host, easiest first (a browser that sandboxes here, an AppArmor profile via `browserhive doctor --printApparmorProfile`, running as a normal user, `sandbox=auto` or `sandbox=off`).',
  }),
  DATA_DIR_UNWRITABLE: defineError({
    code: 'DATA_DIR_UNWRITABLE',
    httpStatus: 500,
    category: 'boot',
    retryable: 'never',
    title: 'Data directory not writable',
    message: 'The data directory {path} is not writable.',
    hint: 'Fix permissions or choose another dataDir.',
    details: z.object({ path: z.string() }),
    docs: true,
    exitCode: 1,
    cause:
      'The data directory could not be created, or is owned by another user. A filesystem that only refuses the 0700 mode is not fatal: boot logs a warning instead.',
    resolution: 'Point `dataDir` at a directory the server user owns.',
  }),
  DATA_DIR_LOCKED: defineError({
    code: 'DATA_DIR_LOCKED',
    httpStatus: 409,
    category: 'boot',
    retryable: 'never',
    title: 'Data directory in use',
    message: 'The data directory {path} is in use by another BrowserHive process (pid {pid}).',
    hint: 'Stop the running server first, or point dataDir at another directory.',
    details: z.object({ path: z.string(), pid: z.number().int() }),
    docs: true,
    exitCode: 3,
    cause:
      'A live process holds `<data-dir>/browserhive.lock`; one server (or one maintenance command) owns a data directory at a time.',
    resolution:
      'Stop that process. A lock left by a crashed process is detected (its pid is gone) and replaced automatically.',
  }),
  DB_OPEN_FAILED: defineError({
    code: 'DB_OPEN_FAILED',
    httpStatus: 500,
    category: 'boot',
    retryable: 'never',
    title: 'Database could not be opened',
    message: 'Cannot open database {path}: {reason}',
    hint: "Run 'browserhive db status' for details.",
    details: z.object({ path: z.string(), reason: z.string() }),
    docs: true,
    exitCode: 1,
    cause: 'SQLite refused to open the file (locked, permissions, wrong application_id).',
    resolution: 'Check for another running server and file permissions.',
  }),
  DB_NEWER_THAN_BINARY: defineError({
    code: 'DB_NEWER_THAN_BINARY',
    httpStatus: 500,
    category: 'boot',
    retryable: 'never',
    title: 'Database newer than this version',
    message:
      'The database schema (v{db_version}, readable from v{min_reader_version}) is newer than this binary supports (v{binary_version}).',
    hint: "Upgrade BrowserHive, or restore the pre-upgrade backup with 'browserhive db restore <file>'.",
    details: z.object({
      db_version: z.number().int(),
      min_reader_version: z.number().int(),
      binary_version: z.number().int(),
      backup_path: z.string().optional(),
    }),
    docs: true,
    exitCode: 3,
    cause:
      'A newer BrowserHive migrated the database past this binary’s compatibility window (D-04).',
    resolution: 'Upgrade, or restore the named backup to downgrade.',
  }),
  MIGRATION_FAILED: defineError({
    code: 'MIGRATION_FAILED',
    httpStatus: 500,
    category: 'boot',
    retryable: 'never',
    title: 'Migration failed',
    message:
      "Migration '{name}' (v{from} → v{to}) failed. The pre-migration backup is at {backup_path}.",
    hint: 'The database was rolled back; report the failure with the log.',
    details: z.object({
      from: z.number().int(),
      to: z.number().int(),
      name: z.string(),
      backup_path: z.string(),
    }),
    docs: true,
    exitCode: 1,
    cause: 'A migration step raised inside the transaction; the transaction was rolled back.',
    resolution: 'File a bug with the log; restore the backup if the database is unusable.',
  }),
  DB_CORRUPT: defineError({
    code: 'DB_CORRUPT',
    httpStatus: 500,
    category: 'boot',
    retryable: 'never',
    title: 'Database corrupt',
    message: 'The database {path} is corrupt; it was moved to {quarantine_path}.',
    hint: "Restore a backup with 'browserhive db restore <file>' or start fresh.",
    details: z.object({ path: z.string(), quarantine_path: z.string() }),
    docs: true,
    exitCode: 1,
    cause: '`PRAGMA quick_check` failed or SQLite reported corruption.',
    resolution: 'Restore the most recent backup from `backups/`.',
  }),
  UNHANDLED: defineError({
    code: 'UNHANDLED',
    httpStatus: 500,
    category: 'boot',
    retryable: 'never',
    title: 'Unhandled error',
    message: 'Unhandled {kind} reached the process handler: {name}.',
    hint: 'Check the log for the stack; the server keeps running when the failure is contained.',
    details: z.object({ kind: z.enum(['exception', 'rejection']), name: z.string() }),
    docs: true,
    exitCode: 1,
    cause:
      'A promise rejected with no handler or an exception escaped every boundary; the CLI process handlers record it as a degradation (spec 10 §3).',
    resolution:
      'Report the log line; repeated occurrences on `/system.degradations` indicate a bug in a background task.',
  }),
  RETENTION_FAILED: defineError({
    code: 'RETENTION_FAILED',
    httpStatus: 500,
    category: 'boot',
    retryable: 'backoff',
    title: 'Retention sweep failed',
    message: 'Retention step {step} failed: {reason}',
    hint: 'The sweep retries on the next interval; check disk space and file permissions.',
    details: z.object({ step: z.string(), reason: z.string() }),
    docs: true,
    exitCode: 1,
    cause:
      'A step of the periodic retention sweep (row pruning, byte cap, vacuum or artifact enqueue) threw. Recorded as a degradation, never fatal.',
    resolution:
      'Fix the underlying cause (disk, permissions, locks); the degradation resolves on the next clean pass.',
  }),
  STALE_BROWSER_PROCESSES: defineError({
    code: 'STALE_BROWSER_PROCESSES',
    httpStatus: 500,
    category: 'boot',
    retryable: 'never',
    title: 'Stale browser processes found',
    message: '{count} browser process(es) from a previous run are still alive.',
    hint: 'Stop them manually if they hold profile locks or memory.',
    details: z.object({ count: z.number().int() }),
    docs: true,
    exitCode: 1,
    cause:
      'Chromium processes launched by an earlier BrowserHive survived its exit (crash or SIGKILL). Recorded as a boot-time degradation, never fatal.',
    resolution: 'Kill the listed processes; they are not adopted by the new server.',
  }),
} as const;
