/** @module contracts/errors/codes-auth-transport — authentication and HTTP/WS transport error codes */
import { z } from 'zod';
import { defineError } from './spec.ts';

/** Authentication and authorization codes (D-09). */
export const AUTH_ERRORS = {
  UNAUTHORIZED: defineError({
    code: 'UNAUTHORIZED',
    httpStatus: 401,
    category: 'auth',
    retryable: 'never',
    title: 'Unauthorized',
    message: 'Authentication required.',
    hint: 'Log in, or send a valid bearer token.',
    details: z.object({}),
    docs: true,
    cause: 'No credential was presented, or the presented one is invalid or expired.',
    resolution: 'Authenticate with the dashboard session cookie or a bearer token.',
  }),
  INVALID_CREDENTIALS: defineError({
    code: 'INVALID_CREDENTIALS',
    httpStatus: 401,
    category: 'auth',
    retryable: 'never',
    title: 'Invalid credentials',
    message: 'Invalid username or password.',
    hint: 'Check the password; reset it with browserhive admin reset-password.',
    details: z.object({}),
    docs: true,
    cause: 'The login password did not match, or the account is locked out.',
    resolution: 'Retry with the correct password or reset it from the CLI.',
  }),
  FORBIDDEN: defineError({
    code: 'FORBIDDEN',
    httpStatus: 403,
    category: 'auth',
    retryable: 'never',
    title: 'Forbidden',
    message: "This action requires the '{scope}' scope.",
    hint: 'Use a principal that holds the scope.',
    details: z.object({ scope: z.string() }),
    docs: true,
    cause: 'The principal lacks the scope the route or tool declares.',
    resolution: 'Operators hold every scope; issue an operator token with the needed scope.',
  }),
  PASSWORD_CHANGE_REQUIRED: defineError({
    code: 'PASSWORD_CHANGE_REQUIRED',
    httpStatus: 403,
    category: 'auth',
    retryable: 'after_operator',
    title: 'Password change required',
    message: 'The seed password must be changed before continuing.',
    hint: 'Change the password on the login screen.',
    details: z.object({}),
    docs: true,
    cause: 'The operator account still uses the generated seed password.',
    resolution: 'Set a new password; the seed file is shredded afterwards.',
  }),
  BAD_CURRENT_PASSWORD: defineError({
    code: 'BAD_CURRENT_PASSWORD',
    httpStatus: 400,
    category: 'auth',
    retryable: 'different_args',
    title: 'Current password incorrect',
    message: 'The current password is incorrect.',
    hint: 'Re-enter the current password.',
    details: z.object({}),
    docs: true,
    cause: 'The password-change request carried a wrong current password.',
    resolution: 'Retry with the correct current password.',
  }),
  WEAK_PASSWORD: defineError({
    code: 'WEAK_PASSWORD',
    httpStatus: 400,
    category: 'auth',
    retryable: 'different_args',
    title: 'Password too weak',
    message: 'The new password must be at least {min_length} characters long.',
    hint: 'Choose a longer password.',
    details: z.object({ min_length: z.number().int() }),
    docs: true,
    cause: 'The new password is shorter than the minimum length.',
    resolution: 'Use at least the minimum number of characters.',
  }),
} as const;

/** HTTP and WebSocket transport codes. */
export const TRANSPORT_ERRORS = {
  ORIGIN_NOT_ALLOWED: defineError({
    code: 'ORIGIN_NOT_ALLOWED',
    httpStatus: 403,
    category: 'transport',
    retryable: 'never',
    title: 'Origin not allowed',
    message: 'The request Origin is not allowed.',
    hint: 'Open the dashboard from the server URL itself.',
    details: z.object({}),
    docs: true,
    cause: 'A browser request carried an `Origin` that does not match the server (CSRF guard).',
    resolution: 'Use the dashboard served by this BrowserHive; no cross-origin access is allowed.',
  }),
  HOST_NOT_ALLOWED: defineError({
    code: 'HOST_NOT_ALLOWED',
    httpStatus: 421,
    category: 'transport',
    retryable: 'never',
    title: 'Host not allowed',
    message: 'The request Host header is not allowed.',
    hint: 'Address the server by the host it is bound to.',
    details: z.object({}),
    docs: true,
    cause: 'DNS-rebinding guard: the `Host` header does not match the bound host.',
    resolution: 'Use the bound host or IP in the URL.',
  }),
  RATE_LIMITED: defineError({
    code: 'RATE_LIMITED',
    httpStatus: 429,
    category: 'transport',
    retryable: 'backoff',
    title: 'Rate limited',
    message: 'Too many requests. Retry after {retry_after_ms} ms.',
    hint: 'Back off for the given interval.',
    details: z.object({ retry_after_ms: z.number().int() }),
    docs: true,
    cause: 'The client exceeded the login or API rate limit.',
    resolution: 'Wait for `retry_after_ms` and retry.',
  }),
  PAYLOAD_TOO_LARGE: defineError({
    code: 'PAYLOAD_TOO_LARGE',
    httpStatus: 413,
    category: 'transport',
    retryable: 'different_args',
    title: 'Payload too large',
    message: 'The request body exceeds the limit of {limit_bytes} bytes.',
    hint: 'Send a smaller body.',
    details: z.object({ limit_bytes: z.number().int() }),
    docs: true,
    cause: 'The body is larger than the route’s limit.',
    resolution: 'Reduce the payload size.',
  }),
  VALIDATION_FAILED: defineError({
    code: 'VALIDATION_FAILED',
    httpStatus: 400,
    category: 'transport',
    retryable: 'different_args',
    title: 'Validation failed',
    message: 'The request failed validation.',
    hint: 'Each issue names the field and what is wrong.',
    details: z.object({
      issues: z.array(z.object({ path: z.string(), message: z.string(), code: z.string() })),
    }),
    docs: true,
    cause: 'Params, query or body did not match the route schema; unknown keys are errors.',
    resolution: 'Fix the listed fields.',
  }),
  NOT_FOUND: defineError({
    code: 'NOT_FOUND',
    httpStatus: 404,
    category: 'transport',
    retryable: 'never',
    title: 'Not found',
    message: 'The requested resource does not exist.',
    hint: 'Check the path and id.',
    details: z.object({}),
    docs: true,
    cause: 'No route or resource matches the request.',
    resolution: 'Consult /api/v1/docs for the route table.',
  }),
  METHOD_NOT_ALLOWED: defineError({
    code: 'METHOD_NOT_ALLOWED',
    httpStatus: 405,
    category: 'transport',
    retryable: 'never',
    title: 'Method not allowed',
    message: 'The method is not allowed for this resource.',
    hint: 'Use one of the allowed methods.',
    details: z.object({ allow: z.array(z.string()) }),
    docs: true,
    cause: 'The route exists but not for this HTTP method.',
    resolution: 'See `details.allow` and the `Allow` header.',
  }),
  CONFLICT: defineError({
    code: 'CONFLICT',
    httpStatus: 409,
    category: 'transport',
    retryable: 'different_args',
    title: 'Conflict',
    message: 'The resource changed since you last read it.',
    hint: 'Reload the resource and retry with the current version.',
    details: z.object({ current_version: z.number().int().optional() }),
    docs: true,
    cause:
      'An optimistic-concurrency check (`If-Match`/version) failed; the HTTP layer may use 412.',
    resolution: 'Re-read, then resubmit with `current_version`.',
  }),
  NOT_ACCEPTABLE: defineError({
    code: 'NOT_ACCEPTABLE',
    httpStatus: 406,
    category: 'transport',
    retryable: 'different_args',
    title: 'Not acceptable',
    message: 'None of the requested media types is supported.',
    hint: 'Ask for one of the supported types.',
    details: z.object({ supported: z.array(z.string()) }),
    docs: true,
    cause: 'The `Accept` header lists no representation the route can produce.',
    resolution: 'See `details.supported`.',
  }),
  WS_PROTOCOL_ERROR: defineError({
    code: 'WS_PROTOCOL_ERROR',
    httpStatus: 400,
    category: 'transport',
    retryable: 'never',
    title: 'WebSocket protocol error',
    message: 'The WebSocket client violated the protocol.',
    hint: 'Reconnect with a compliant client.',
    details: z.object({ violations: z.array(z.string()) }),
    docs: true,
    cause:
      'Malformed envelope, unknown command, wrong protocol version, or a command before subscribe.',
    resolution: 'Fix the client; the socket is closed with the code in spec 03 §6.4.',
  }),
  WS_OVERLOADED: defineError({
    code: 'WS_OVERLOADED',
    httpStatus: 503,
    category: 'transport',
    retryable: 'backoff',
    title: 'WebSocket overloaded',
    message: 'The connection fell too far behind ({buffered_bytes} bytes buffered).',
    hint: 'Reconnect and resubscribe with the last cursor.',
    details: z.object({ buffered_bytes: z.number().int() }),
    docs: true,
    cause: 'Backpressure: the client did not drain the feed within the buffer bounds.',
    resolution: 'Reconnect; the feed replays from your cursor or asks for a resync.',
  }),
} as const;
