/** @module contracts/errors/codes-service — vault, operator-request, live-view and dispatcher codes */
import { z } from 'zod';
import { defineError } from './spec.ts';

const sessionId = z.object({ session_id: z.string() });

/** Vault, operator-request, live-view and dispatcher codes. */
export const SERVICE_ERRORS = {
  VAULT_NOT_CONFIGURED: defineError({
    code: 'VAULT_NOT_CONFIGURED',
    httpStatus: 404,
    category: 'domain',
    retryable: 'never',
    title: 'No vault configured',
    message: 'No vault backend is configured. Start the server with --vault <backend>.',
    hint: 'Ask the operator to start the server with vault=bitwarden.',
    details: z.object({}),
    docs: true,
    cause: 'The server runs with `vault=off`.',
    resolution: 'Start with `--vault bitwarden` and unlock it.',
  }),
  VAULT_LOCKED: defineError({
    code: 'VAULT_LOCKED',
    httpStatus: 409,
    category: 'domain',
    retryable: 'after_operator',
    title: 'Vault locked',
    message: 'Vault backend is locked. Unlock it on the dashboard Vault page.',
    hint: 'Ask the operator to unlock the vault, then retry.',
    details: z.object({ backend: z.string() }),
    docs: true,
    cause: 'The backend session token is absent or expired.',
    resolution:
      'Run `bw unlock --raw` and paste the session token on the dashboard Vault page, or restart the server with `BW_SESSION` exported.',
  }),
  VAULT_ENTRY_NOT_FOUND: defineError({
    code: 'VAULT_ENTRY_NOT_FOUND',
    httpStatus: 404,
    category: 'domain',
    retryable: 'different_args',
    title: 'Vault entry not found',
    message: "Vault entry '{entry_name}' is not in the backend.",
    hint: 'Use vault_list_available to see entries you may fill.',
    details: z.object({ entry_name: z.string() }),
    docs: true,
    cause: 'No binding or backend item matches the requested entry name.',
    resolution: 'Pick a name from vault_list_available, or ask the operator to bind the item.',
  }),
  VAULT_NOT_AUTHORIZED: defineError({
    code: 'VAULT_NOT_AUTHORIZED',
    httpStatus: 403,
    category: 'domain',
    retryable: 'never',
    title: 'Vault entry not authorized',
    message: "Vault entry '{entry_name}' is not authorized for this session's slug.",
    hint: 'The operator controls which sessions may use this entry.',
    details: z.object({ entry_name: z.string() }),
    docs: true,
    cause: 'The binding or group policy does not allow this principal and session slug.',
    resolution: 'Operators edit the binding (slug globs, principals) on the Vault page.',
  }),
  EVALUATE_REQUIRED_OFF: defineError({
    code: 'EVALUATE_REQUIRED_OFF',
    httpStatus: 403,
    category: 'domain',
    retryable: 'never',
    title: 'Entry requires evaluate disabled',
    message:
      "Vault entry '{entry_name}' requires the session to have evaluate disabled (launch with disable_evaluate: true).",
    hint: 'Relaunch the session with disable_evaluate: true.',
    details: z.object({ entry_name: z.string() }),
    docs: true,
    cause: 'The binding is marked `require_no_evaluate` and the session can run scripts.',
    resolution: 'Launch with `disable_evaluate: true` before filling this entry.',
  }),
  DASHBOARD_DENIED: defineError({
    code: 'DASHBOARD_DENIED',
    httpStatus: 403,
    category: 'domain',
    retryable: 'after_operator',
    title: 'Fill denied by operator',
    message:
      "Vault fill for '{entry_name}' was denied by the dashboard (or timed out waiting for confirmation).",
    hint: 'Ask the operator to approve the fill, then retry.',
    details: z.object({ request_id: z.string(), entry_name: z.string().optional() }),
    docs: true,
    cause: 'The operator rejected the confirmation, or nobody answered before the deadline.',
    resolution: 'Retry when an operator is available to confirm.',
  }),
  VAULT_UNLOCK_FAILED: defineError({
    code: 'VAULT_UNLOCK_FAILED',
    httpStatus: 401,
    category: 'domain',
    retryable: 'different_args',
    title: 'Vault unlock failed',
    message: 'Vault unlock failed ({mode}).',
    hint: 'Create a new session token with `bw unlock --raw` and paste it again.',
    details: z.object({ mode: z.string() }),
    docs: true,
    cause:
      'The backend rejected the session token (expired after `bw lock` or `bw logout`, or from another `bw` login), or the passphrase of a passphrase backend.',
    resolution:
      'Run `bw unlock --raw` as the user that runs BrowserHive and paste the new token, or export it as `BW_SESSION` before start.',
  }),
  VAULT_SYNC_UNSUPPORTED: defineError({
    code: 'VAULT_SYNC_UNSUPPORTED',
    httpStatus: 400,
    category: 'domain',
    retryable: 'never',
    title: 'Vault sync unsupported',
    message: "Vault backend '{backend}' does not support sync.",
    hint: 'Nothing to do; this backend has no sync operation.',
    details: z.object({ backend: z.string() }),
    docs: true,
    cause: 'The backend capabilities report `sync: false`.',
    resolution: 'Use a backend that supports sync, or skip the call.',
  }),
  VAULT_BACKEND_ERROR: defineError({
    code: 'VAULT_BACKEND_ERROR',
    httpStatus: 502,
    category: 'domain',
    retryable: 'backoff',
    title: 'Vault backend error',
    message: "Vault backend '{backend}' failed ({kind}).",
    hint: 'Retry; if it persists, check the backend CLI on the host.',
    details: z.object({ backend: z.string(), kind: z.enum(['not_installed', 'timeout', 'exit']) }),
    docs: true,
    cause: 'The backend CLI is missing, timed out, or exited with an error.',
    resolution: 'Install or repair the backend CLI (`bw`) and retry.',
  }),
  ATTENTION_REQUIRES_HTTP: defineError({
    code: 'ATTENTION_REQUIRES_HTTP',
    httpStatus: 400,
    category: 'domain',
    retryable: 'never',
    title: 'Attention requires http',
    message:
      "'{tool}' requires the http transport; human-in-the-loop attention is not available under stdio.",
    hint: 'Run the server with transport=http and admin=true.',
    details: z.object({ tool: z.string() }),
    docs: true,
    cause:
      'Attention needs the shared, long-lived HTTP daemon and the dashboard; stdio is single-client.',
    resolution: 'Start BrowserHive with `--admin` (http transport).',
  }),
  ATTENTION_NOT_OPEN: defineError({
    code: 'ATTENTION_NOT_OPEN',
    httpStatus: 409,
    category: 'domain',
    retryable: 'never',
    title: 'Attention request is not open',
    message: "Attention request '{request_id}' is not open (status: {status}).",
    hint: 'Refresh the queue.',
    details: z.object({ request_id: z.string(), status: z.string() }),
    docs: true,
    cause: 'The request was already resolved, rejected, timed out or cancelled.',
    resolution: 'Nothing to do; the outcome is final.',
  }),
  CONFIRM_NOT_OPEN: defineError({
    code: 'CONFIRM_NOT_OPEN',
    httpStatus: 409,
    category: 'domain',
    retryable: 'never',
    title: 'Confirmation is not open',
    message: "Vault confirmation '{request_id}' is not open (status: {status}).",
    hint: 'Refresh the confirm queue.',
    details: z.object({ request_id: z.string(), status: z.string() }),
    docs: true,
    cause: 'The confirmation was already decided or expired.',
    resolution: 'Nothing to do; the outcome is final.',
  }),
  INPUT_NOT_PERMITTED: defineError({
    code: 'INPUT_NOT_PERMITTED',
    httpStatus: 409,
    category: 'domain',
    retryable: 'after_operator',
    title: 'Input not permitted',
    message:
      "Input is not permitted on session '{session_id}': no takeover attention request is open.",
    hint: 'Input is only accepted while a takeover attention request is open.',
    details: sessionId,
    docs: true,
    cause: 'Live-view input is gated on an open `takeover` request from the agent.',
    resolution: 'Wait for the agent to request attention in takeover mode.',
  }),
  SCREENCAST_FAILED: defineError({
    code: 'SCREENCAST_FAILED',
    httpStatus: 502,
    category: 'domain',
    retryable: 'backoff',
    title: 'Screencast failed',
    message: "Screencast for session '{session_id}' failed: {reason}",
    hint: 'Retry; if the session is closing the stream cannot start.',
    details: z.object({ session_id: z.string(), reason: z.string() }),
    docs: true,
    cause: 'The CDP screencast could not be started or the bridge lost its page.',
    resolution: 'Retry the live view; check the session is live.',
  }),
  TOOL_NOT_AVAILABLE: defineError({
    code: 'TOOL_NOT_AVAILABLE',
    httpStatus: 400,
    category: 'domain',
    retryable: 'never',
    title: 'Tool not available',
    message: "Tool '{tool}' is not available on this server (requires {requires}).",
    hint: 'The tool needs a server feature that is off.',
    details: z.object({ tool: z.string(), requires: z.string() }),
    docs: true,
    cause: 'The tool pack requires a transport, vault or admin feature that is not enabled.',
    resolution: 'Enable the feature on the server, or avoid the tool.',
  }),
  INVALID_ARGUMENTS: defineError({
    code: 'INVALID_ARGUMENTS',
    httpStatus: 400,
    category: 'domain',
    retryable: 'different_args',
    title: 'Invalid arguments',
    message: 'Invalid arguments: {summary}',
    hint: 'Fix the listed issues and call the tool again.',
    details: z.object({
      issues: z.array(z.object({ path: z.string(), message: z.string() })),
    }),
    docs: true,
    cause: 'The tool arguments failed schema validation.',
    resolution: 'Each issue names the path and what is wrong.',
  }),
  TRACE_UNAVAILABLE: defineError({
    code: 'TRACE_UNAVAILABLE',
    httpStatus: 404,
    category: 'domain',
    retryable: 'never',
    title: 'Trace unavailable',
    message: 'No trace is available for this session.',
    hint: 'Tracing is on when trace=true (default with admin).',
    details: z.object({ enabled: z.boolean() }),
    docs: true,
    cause: 'Tracing was off for the session, or the trace failed to finalize.',
    resolution: 'Enable `trace` and relaunch; see TRACE_START_FAILED warnings.',
  }),
  SCREENSHOT_UNAVAILABLE: defineError({
    code: 'SCREENSHOT_UNAVAILABLE',
    httpStatus: 404,
    category: 'domain',
    retryable: 'never',
    title: 'Screenshot unavailable',
    message: "No screenshot is stored for event '{event_id}'.",
    hint: 'Screenshots are kept per tool call while retention allows.',
    details: z.object({ event_id: z.string() }),
    docs: true,
    cause: 'The event produced no screenshot, or retention removed it.',
    resolution: 'Nothing to do; the artifact no longer exists.',
  }),
  INTERNAL_ERROR: defineError({
    code: 'INTERNAL_ERROR',
    httpStatus: 500,
    category: 'domain',
    retryable: 'backoff',
    title: 'Internal error',
    message: 'Internal error (ref {ref}).',
    hint: 'Quote the ref to the operator; the logs hold the detail.',
    details: z.object({ ref: z.string() }),
    docs: true,
    cause: 'An unexpected failure that no typed code describes.',
    resolution: 'Search the logs for the ref (request id) and file a bug if it repeats.',
  }),
} as const;
