/** @module contracts/errors/codes-page — interaction, navigation, evaluation and browser fault codes */
import { z } from 'zod';
import { defineError } from './spec.ts';

const sessionId = z.object({ session_id: z.string() });

/** Interaction, navigation, evaluation and browser fault codes. */
export const PAGE_ERRORS = {
  EVALUATE_DISABLED: defineError({
    code: 'EVALUATE_DISABLED',
    httpStatus: 403,
    category: 'domain',
    retryable: 'never',
    title: 'evaluate is disabled',
    message: "The 'evaluate' tool is disabled for session '{session_id}'.",
    hint: 'Use the structured tools (click, fill, get_content, snapshot) instead.',
    details: z.object({ session_id: z.string(), scope: z.enum(['session', 'server']) }),
    docs: true,
    cause:
      'The session was launched with `disable_evaluate: true`, or the server runs with `allowEvaluate=false`.',
    resolution:
      'Relaunch without `disable_evaluate`, or ask the operator to enable `allowEvaluate`.',
  }),
  ELEMENT_NOT_ACTIONABLE: defineError({
    code: 'ELEMENT_NOT_ACTIONABLE',
    httpStatus: 422,
    category: 'domain',
    retryable: 'backoff',
    title: 'Element not actionable',
    // Core appends " ({detail})" when a driver detail (first line, ≤ 160 chars) is available.
    message:
      "Element '{selector}' did not become actionable within the timeout — it may be hidden, detached, disabled, covered by another element, or the selector matched the wrong element. Use a more specific, visible selector, or raise the timeout.",
    hint: 'Take a snapshot to find a visible, unique selector; raise timeout_ms if the page is slow.',
    details: z.object({ selector: z.string(), detail: z.string().optional() }),
    docs: true,
    cause:
      'The target was hidden, detached, disabled, covered, or the selector matched the wrong element.',
    resolution: 'Use a more specific selector or wait for the element to become visible first.',
  }),
  ELEMENT_NOT_FOUND: defineError({
    code: 'ELEMENT_NOT_FOUND',
    httpStatus: 404,
    category: 'domain',
    retryable: 'different_args',
    title: 'Element not found',
    message: "No element matched selector '{selector}'.",
    hint: 'Take a snapshot and pick a selector that matches exactly one element.',
    details: z.object({ selector: z.string(), count: z.number().int().optional() }),
    docs: true,
    cause: 'The selector matched nothing, or matched several elements under strict mode.',
    resolution: 'Refine the selector; `count` in details tells you how many matched.',
  }),
  NAVIGATION_TIMEOUT: defineError({
    code: 'NAVIGATION_TIMEOUT',
    httpStatus: 504,
    category: 'domain',
    retryable: 'backoff',
    title: 'Navigation timed out',
    message: "Navigation to '{url}' did not finish within {timeout_ms} ms.",
    hint: 'Retry with a longer timeout_ms or a lighter wait_until (commit, domcontentloaded).',
    details: z.object({ url: z.string(), timeout_ms: z.number().int() }),
    docs: true,
    cause: 'The page did not reach the requested load state before the timeout.',
    resolution: 'Raise the timeout, choose an earlier `wait_until`, or check the network.',
  }),
  NAVIGATION_FAILED: defineError({
    code: 'NAVIGATION_FAILED',
    httpStatus: 502,
    category: 'domain',
    retryable: 'backoff',
    title: 'Navigation failed',
    message: "Navigation to '{url}' failed ({net_error}).",
    hint: 'Check the URL and network; net_error names the Chromium failure.',
    details: z.object({ url: z.string(), net_error: z.string() }),
    docs: true,
    cause:
      'Chromium reported a network error (`net::ERR_*`): DNS, TLS, connection refused, and so on.',
    resolution: 'Verify the URL resolves and is reachable from the host; retry transient failures.',
  }),
  WAIT_TIMEOUT: defineError({
    code: 'WAIT_TIMEOUT',
    httpStatus: 504,
    category: 'domain',
    retryable: 'backoff',
    title: 'Wait timed out',
    message: 'Timed out after {timeout_ms} ms waiting for {what}.',
    hint: 'Raise timeout_ms or wait for a different condition.',
    details: z.object({ what: z.string(), timeout_ms: z.number().int() }),
    docs: true,
    cause: 'The awaited selector state, URL or load state did not occur in time.',
    resolution: 'Check the page state with snapshot, then wait for a condition that will happen.',
  }),
  SCRIPT_ERROR: defineError({
    code: 'SCRIPT_ERROR',
    httpStatus: 422,
    category: 'domain',
    retryable: 'different_args',
    title: 'Script threw',
    message: 'The evaluated script threw: {message}',
    hint: 'Fix the script; the first line of the page error is in details.message.',
    details: z.object({ message: z.string() }),
    docs: true,
    cause: 'The expression passed to `evaluate` threw inside the page.',
    resolution: 'Correct the script or guard against missing globals.',
  }),
  DOWNLOAD_FAILED: defineError({
    code: 'DOWNLOAD_FAILED',
    httpStatus: 502,
    category: 'domain',
    retryable: 'backoff',
    title: 'Download failed',
    message: 'Download failed: {reason}',
    hint: 'Retry; if it persists, check that the link starts a download.',
    details: z.object({ reason: z.string() }),
    docs: true,
    cause: 'The browser reported the download as failed or cancelled.',
    resolution: 'Retry the download; verify the target actually serves a file.',
  }),
  UPLOAD_FAILED: defineError({
    code: 'UPLOAD_FAILED',
    httpStatus: 422,
    category: 'domain',
    retryable: 'different_args',
    title: 'Upload failed',
    message: 'Upload failed: {reason}',
    hint: 'Check that the selector targets a file input and the file exists under uploads/.',
    details: z.object({ reason: z.string() }),
    docs: true,
    cause:
      '`setInputFiles` failed: wrong element, missing file, or a page that rejected the input.',
    resolution: 'Target an `<input type=file>` and place the file in the uploads directory.',
  }),
  PAGE_CLOSED: defineError({
    code: 'PAGE_CLOSED',
    httpStatus: 410,
    category: 'domain',
    retryable: 'different_args',
    title: 'Page closed',
    message: "Tab '{tab_id}' was closed while the action was running.",
    hint: 'Use list_tabs and target an open tab.',
    details: z.object({ tab_id: z.string() }),
    docs: true,
    cause:
      'The page or its execution context was destroyed mid-call (closed tab, navigation away).',
    resolution: 'Re-open or re-target the tab and retry.',
  }),
  BROWSER_CRASHED: defineError({
    code: 'BROWSER_CRASHED',
    httpStatus: 500,
    category: 'domain',
    retryable: 'after_operator',
    title: 'Browser crashed',
    message: "The browser behind session '{session_id}' crashed.",
    hint: 'Launch a new session; the crashed one will be reaped.',
    details: sessionId,
    docs: true,
    cause: 'The browser context or process was closed unexpectedly.',
    resolution: 'Launch a replacement session; check host memory if it repeats.',
  }),
  URL_BLOCKED: defineError({
    code: 'URL_BLOCKED',
    httpStatus: 403,
    category: 'domain',
    retryable: 'never',
    title: 'URL blocked by policy',
    message:
      "The URL '{url}' is blocked by the administrator (matched the blocklist pattern '{pattern}'). This is an operator policy, not a transient failure — do not retry this URL, and do not try to reach it by another route. Report it to the user if the task cannot continue.",
    hint: 'Do not retry; report the block to the user.',
    details: z.object({ url: z.string(), pattern: z.string() }),
    docs: true,
    cause: 'The URL matched a pattern in the operator blocklist (`blocklist` file).',
    resolution: 'Operators edit the blocklist file (reloaded live) if the block is unintended.',
  }),
  BROWSER_NOT_INSTALLED: defineError({
    code: 'BROWSER_NOT_INSTALLED',
    httpStatus: 503,
    category: 'domain',
    retryable: 'after_operator',
    title: 'Browser not installed',
    message:
      "No browser is installed for channel '{channel}'. Run '{install_command}' on the host.",
    hint: 'Ask the operator to run browserhive init.',
    details: z.object({ channel: z.string(), install_command: z.string() }),
    docs: true,
    cause: 'The Chromium binary for the driver/channel is missing (no postinstall download, D-18).',
    resolution: 'Run `browserhive init`, or install the branded browser for `chrome`/`edge`.',
  }),
} as const;
