/** @module ports/persistence — public surface of the persistence ports (spec 03 §7.2). */

export type {
  ActivityBucket,
  ActivityQuery,
  ActivityResult,
  ActivitySummary,
  AnalyticsQueries,
  TimelineItem,
  TimelineKind,
  TimelineQuery,
  ToolMetricsQuery,
  ToolMetricsRow,
} from './analytics.ts';
export type { BlockedRequestListRow, BlocklistAuditRepository } from './blocklist-audit.ts';
export type {
  ActorKind,
  ArtifactKind,
  AttentionMode,
  AuthEventType,
  BlockSource,
  ClosedReason,
  CredentialKind,
  McpTransport,
  NotificationType,
  OperatorRequestKind,
  OperatorRequestStatus,
  OriginCheck,
  PageCategory,
  PersistenceMode,
  PrincipalKind,
  ScreenshotKind,
  SessionChannel,
  SessionEngine,
  SessionState,
  SystemEventSeverity,
  VaultAccessMode,
  VaultAccessResult,
} from './enums.ts';
export {
  ACTOR_KINDS,
  ARTIFACT_KINDS,
  ATTENTION_MODES,
  AUTH_EVENT_TYPES,
  BLOCK_SOURCES,
  CLOSED_REASONS,
  CREDENTIAL_KINDS,
  MCP_TRANSPORTS,
  NOTIFICATION_TYPES,
  OPERATOR_REQUEST_KINDS,
  OPERATOR_REQUEST_STATUSES,
  ORIGIN_CHECKS,
  PAGE_CATEGORIES,
  PERSISTENCE_MODES,
  PRINCIPAL_KINDS,
  SCREENSHOT_KINDS,
  SESSION_CHANNELS,
  SESSION_ENGINES,
  SESSION_STATES,
  SYSTEM_EVENT_SEVERITIES,
  VAULT_ACCESS_MODES,
  VAULT_ACCESS_RESULTS,
} from './enums.ts';
export type { EventLogRepository } from './event-log.ts';
export type {
  AuthEventRepository,
  AuthSessionRepository,
  CredentialRepository,
  GrantRepository,
  PrincipalPatch,
  PrincipalRepository,
} from './identity.ts';
export type {
  IntegrityResult,
  MaintenanceService,
  MigrationResult,
  PurgeInventory,
  RetentionFailure,
  RetentionPolicy,
  RetentionResult,
} from './maintenance.ts';
export type { NotificationRepository, PreferenceRepository } from './notifications.ts';
export type {
  ArtifactOutboxRepository,
  IdempotencyRepository,
  LogRepository,
  McpConnectionPatch,
  McpConnectionRepository,
  OperatorActionRepository,
  SchemaMigrationRepository,
  SystemEventRepository,
} from './operations.ts';
export type {
  OperatorRequestListRow,
  OperatorRequestRepository,
  OperatorRequestResolution,
} from './operator-requests.ts';
export type { DomainCount, PageListRow, PageRepository } from './pages.ts';
export type {
  AuditListQuery,
  BlockedRequestListQuery,
  BlockedStats,
  FacetCount,
  NotificationListQuery,
  OperatorRequestListQuery,
  Page,
  PageListQuery,
  PageQuery,
  ScreenshotListQuery,
  SessionFacets,
  SessionListQuery,
  SessionSortKey,
  SortDir,
  SystemEventListQuery,
  TimeWindow,
  ToolCallListQuery,
  TopDomainsQuery,
  VaultAccessListQuery,
  VaultBindingListQuery,
} from './queries.ts';
export type {
  ArtifactOutboxRecord,
  AuthEventRecord,
  AuthSessionRecord,
  BlockedRequestRecord,
  CredentialRecord,
  EventRecord,
  GrantRecord,
  HarnessConflictRecord,
  IdempotencyRecord,
  JsonObject,
  JsonValue,
  LogRecordRow,
  McpConnectionRecord,
  NewArtifact,
  NewAuthEvent,
  NewEvent,
  NewOperatorAction,
  NewOperatorRequest,
  NewSystemEvent,
  NotificationGroupPatch,
  NotificationRecord,
  OperatorActionRecord,
  OperatorRequestRecord,
  PageRecord,
  PreferenceRecord,
  PrincipalRecord,
  SchemaMigrationRecord,
  ScreenshotRecord,
  SessionCounts,
  SessionListRow,
  SessionPatch,
  SessionRecord,
  SystemEventRecord,
  ToolCallRecord,
  VaultAccessRecord,
  VaultBindingRecord,
  VaultExportDocument,
  VaultGroupPolicyRecord,
} from './records.ts';
export type { ScreenshotListRow, ScreenshotRepository } from './screenshots.ts';
export type { SessionDeleteResult, SessionRepository } from './sessions.ts';
export type { ToolCallListRow, ToolCallRepository } from './tool-calls.ts';
export type { Repositories, UnitOfWork } from './unit-of-work.ts';
export type { VaultAccessListRow, VaultAuditRepository } from './vault-audit.ts';
export type {
  VaultBindingRepository,
  VaultGroupPolicyRepository,
  VaultImportMode,
  VaultImportResult,
} from './vault-policy.ts';
export type { WriteJob, WriteQueue } from './write-queue.ts';
